---
title: 'Figure 3: '
author: "Juliette"
date: "11/17/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

Figure 3: Overlap maps 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(sf)
library(scales)
library(rnaturalearth)
library(rnaturalearthdata)
library(rasterVis)
library(sf)
library(cowplot)
library(patchwork)


source(here("_workflow/common.R"))
source(here("_workflow/common_spatial.R"))
source(here("_analysis/figures/paper/colors_stressors_fig_1_2.R"))

## save the gall peters projection
gall_peters <- "+proj=cea +lon_0=0 +x_0=0 +y_0=0 +lat_ts=45 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"

## create a water raster
water <- readOGR(dsn = here("_analysis/raw/rgn_all_gcs_med_res.shp"))
water <- water[!water$rgn_nam == "Antarctica",]
proj4string(water) <- CRS("+proj=longlat +datum=WGS84")
water <- spTransform(water, CRS("+proj=cea +lon_0=0 +x_0=0 +y_0=0 +lat_ts=45 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"))
plot(water)

## create a land raster
land <- ne_countries(scale = "medium", returnclass = "sp") 
land <- land[!land$sov_a3 == "ATA",]
land <- st_as_sf(land)
land <- st_transform(land, crs=gall_peters)
land_for_ggplot <- st_transform(land, crs=gall_peters)
land <- as(land, "Spatial")
plot(land)

library(RColorBrewer)
display.brewer.all()


```

## Read in all the pressure rasters and get the quantile breakdowns
```{r}
water_chi <- raster(list.files("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/stressor_summary/equal_area/stressor_per_km2/stressor", pattern = "water", full=TRUE))
 water_quant_1 <- quantile(water_chi, 0.99)
 
ghg_chi <- raster(list.files("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/stressor_summary/equal_area/stressor_per_km2/stressor", pattern = "ghg", full=TRUE))
 ghg_quant_1 <- quantile(ghg_chi, 0.99)
 
dist_chi <- raster(list.files("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/stressor_summary/equal_area/stressor_per_km2/stressor", pattern = "disturbance", full=TRUE))
 dist_quant_1 <- quantile(dist_chi, 0.99) 
 
nut_chi <- raster(list.files("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/stressor_summary/equal_area/stressor_per_km2/stressor", pattern = "nutrient", full=TRUE))
 nut_quant_1 <- quantile(nut_chi, 0.99)  

```

Colors 
```{r}
pal <- c("#7E3235", "#E2694A", "#AECFB6", "#484456", "#F8F9FA")
```

Create overlap map for the top 1%

```{r}

water_chi_1 <- calc(water_chi, fun=function(x){ifelse(x >= water_quant_1, 1, 0)})
ghg_chi_1 <- calc(ghg_chi, fun=function(x){ifelse(x >= ghg_quant_1, 1, 0)})
dist_chi_1 <- calc(dist_chi, fun=function(x){ifelse(x >= dist_quant_1, 1, 0)})
nut_chi_1 <- calc(nut_chi, fun=function(x){ifelse(x >= nut_quant_1, 1, 0)})

overlap_1 <- sum(stack(water_chi_1, ghg_chi_1, dist_chi_1, nut_chi_1), na.rm=TRUE)

## save the map
png(here(sprintf("_analysis/figures/paper/output/fig_3_subsets/explore_overlap_1.png")), res=500, width=7, height=3, units="in")
  par(oma=c(1,0,1,0), new = TRUE, mar=c(0, 0, 1, 0))  # bottom, left, top, and right
  #par(mfrow=c(1, 1), mar=c(1, 0, 1, 2))
plot(water, border = "#FFFFFF", col= "#FFFFFF", lwd=0.5,  cex= 0.75, main= "Top 1%") 

plot(overlap_1,
     add=TRUE,
     col = rev(pal))

plot(land, border = "#f2cc8f", col= "#F8F9FA00", lwd=0.2, add=TRUE)
dev.off()

```


Color palette for identifying which pressures at x1 or x2

```{r}
## x1
# wat_blue <- "#6BBAE5"
# ghg_yellow <- "#E8C534"
# dis_pink <- "#EC8FA3"
# nut_camo <- "#80792B"
# 
# ## x2
# wat_ghg_maroon <- "#682C38"
# wat_dist_purple <- "#62589F"
# wat_nut_lightgreen <- "#93AD90"
# dis_ghg_darkgreen <- "#40663F"
# nut_ghg_salmon <- "#B4674F"
# dis_nut_orange <- "#EB8D43"


wat_blue <- "#6BBAE5"
ghg_pink <- "#EC8FA3"
dis_yellow <- "#E8C534"
nut_salmon <- "#B4674F"

## x2
wat_ghg_maroon <- "#682C38"
wat_dist_purple <- "#62589F"
wat_nut_lightgreen <- "#93AD90"
dis_ghg_darkgreen <- "#40663F"
nut_ghg_camo <- "#80792B"
dis_nut_orange <- "#EB8D43"

## x3
gray1 <- "#C8C8C8"

## x4
gray2 <- "#6C6D71"

col_pal <- c(wat_blue, ghg_pink, dis_yellow, nut_salmon,
             wat_ghg_maroon, wat_dist_purple, wat_nut_lightgreen, dis_ghg_darkgreen, nut_ghg_camo, dis_nut_orange,
             gray1, gray2)

show_col(col_pal)

## create a df that we can use to assign colors
color_assign_df <- as_tibble(col_pal) %>% 
  rename(hex_code = value) %>% 
  mutate(color_assign = case_when(hex_code == wat_blue ~ 1,
                                  hex_code == ghg_pink ~ 2,
                                  hex_code == dis_yellow ~ 3,
                                  hex_code == nut_salmon ~ 4,
                                  
                                  hex_code == wat_ghg_maroon ~ 5,
                                  hex_code == wat_dist_purple ~ 6,
                                  hex_code == wat_nut_lightgreen ~ 7,
                                  hex_code == dis_ghg_darkgreen ~ 8,
                                  hex_code == nut_ghg_camo ~ 9,
                                  hex_code == dis_nut_orange ~  10,
                                  
                                  hex_code == gray1 ~ 11,
                                  hex_code == gray2 ~ 12))

```


Some data wrangling to get the colors to work
```{r}
## make each pressure as a df
water_df <- calc(water_chi, fun=function(x){ifelse(x >= water_quant_1, 1, 0)}) %>% 
  as.data.frame(xy= TRUE) %>% 
  rename(wat = layer)
  
ghg_df <- calc(ghg_chi, fun=function(x){ifelse(x >= ghg_quant_1, 1, 0)}) %>% 
    as.data.frame(xy= TRUE) %>% 
  rename(ghg = layer)

dist_df <- calc(dist_chi, fun=function(x){ifelse(x >= dist_quant_1, 1, 0)}) %>% 
    as.data.frame(xy= TRUE) %>% 
  rename(dis = layer)

nut_df <- calc(nut_chi, fun=function(x){ifelse(x >= nut_quant_1, 1, 0)}) %>% 
    as.data.frame(xy= TRUE) %>% 
  rename(nut = layer)

## combine all into 1
combined_raw <- left_join(water_df, ghg_df) %>% 
  left_join(dist_df) %>% 
  left_join(nut_df)
```

Wrangle for color coding

```{r}
combined <- combined_raw %>% 
  mutate(overlap_count = rowSums((combined_raw[,3:6]), na.rm = TRUE)) %>% 
  mutate(color_assign = case_when(wat == 1 & ghg == 0 & dis == 0 & nut == 0 ~ 1,
                                  wat == 0 & ghg == 1 & dis == 0 & nut == 0 ~ 2,
                                  wat == 0 & ghg == 0 & dis == 1 & nut == 0 ~ 3,
                                  wat == 0 & ghg == 0 & dis == 0 & nut == 1 ~ 4,
                                  
                                  wat == 1 & ghg == 1 & dis == 0 & nut == 0 ~ 5,
                                  wat == 1 & ghg == 0 & dis == 1 & nut == 0 ~ 6,
                                  wat == 1 & ghg == 0 & dis == 0 & nut == 1 ~ 7,
                                  wat == 0 & ghg == 1 & dis == 1 & nut == 0 ~ 8,
                                  wat == 0 & ghg == 1 & dis == 0 & nut == 1 ~ 9,
                                  wat == 0 & ghg == 0 & dis == 1 & nut == 1 ~ 10,
                                  
                                  overlap_count == 3 ~ 11,
                                  overlap_count == 4 ~ 12)) %>% 
  left_join(color_assign_df) %>% 
  mutate(hex_code = ifelse(is.na(hex_code), "#FFFFFF00", hex_code))

#Make a raster with the new colors
combined_rast <- combined %>% 
  select(x,y, color_assign) %>% 
  rasterFromXYZ(crs = gall_peters)
```

Plot
```{r}

png(here("_analysis/figures/paper/output/fig_3_subsets/explore_overlap_colors.png"), res=500, width=7, height=3, units="in")
  par(oma=c(1,0,1,0), new = TRUE, mar=c(0, 0, 1, 0))  # bottom, left, top, and right
  #par(mfrow=c(1, 1), mar=c(1, 0, 1, 2))
  
plot(water, border = "#FFFFFF", col= "#FFFFFF", lwd=0.5,  cex= 0.75, main= "Top 1%") 

plot(combined_rast,
     add=TRUE,
     col = col_pal)

plot(land, border = "black", col= "#F8F9FA00", lwd=0.2, add=TRUE)
dev.off()
```


Pull out a few important looking areas

India
```{r}
library(rgeos)
e_ind <- as(extent(5200000, 7500000, 3000000, 6500000), 'SpatialPolygons')

crs(e_ind) <- crs(combined_rast)

india <- crop(combined_rast, e_ind)

plot(india)
plot(combined_rast)
plot(land)

#land_ind <- raster::crop(land, india) ## the croping of land is't working anymore which is odd. still works without cropping but still... odd 

png(here("_analysis/figures/paper/output/explore_overlap_colors_india.png"), res=500, width=5, height=6, units="in")
  par(oma=c(1,0,1,0), new = TRUE, mar=c(0, 0, 1, 0))  # bottom, left, top, and right
  #par(mfrow=c(1, 1), mar=c(1, 0, 1, 2))
  
#plot(water, border = "#FFFFFF", col= "#FFFFFF", lwd=0.5,  cex= 0.75, main= "Top 1%") 

plot(india,
     col = col_pal,
     axes = FALSE,
     legend = FALSE)
    # bty="n", box=FALSE)

plot(land, border = "black", col= "#F8F9FA00", lwd=0.2, add=TRUE,
     axes = FALSE,
     legend = FALSE,
     bty="n", box=FALSE)
dev.off()

```
USA
```{r}

e_usa <- as(extent(-8000000, -6500000, 5000000, 6500000), 'SpatialPolygons')
crs(e_usa) <- crs(combined_rast)

usa <- crop(combined_rast, e_usa)

plot(usa)
plot(combined_rast)

#land_usa <- crop(land, e_usa) # same issue as with India

png(here("_analysis/figures/paper/output/explore_overlap_colors_usa.png"), res=500, width=7, height=3, units="in")
  par(oma=c(1,0,1,0), new = TRUE, mar=c(0, 0, 1, 0))  # bottom, left, top, and right
  #par(mfrow=c(1, 1), mar=c(1, 0, 1, 2))
  
#plot(water, border = "#FFFFFF", col= "#FFFFFF", lwd=0.5,  cex= 0.75, main= "Top 1%") 

plot(usa,
     col = col_pal)

plot(land, border = "black", col= "#F8F9FA00", lwd=0.2, add=TRUE)
dev.off()

```

Europe
```{r}
e_europe <- as(extent(-900000, 900000, 6500000, 7500000), 'SpatialPolygons')
crs(e_usa) <- crs(combined_rast)

europe <- crop(combined_rast, e_europe)

plot(europe)
plot(combined_rast)

# land_europe <- crop(land, e_europe) same issue as with India/USA

png(here("_analysis/figures/paper/output/explore_overlap_colors_europe.png"), res=500, width=7, height=3, units="in")
  par(oma=c(1,0,1,0), new = TRUE, mar=c(0, 0, 1, 0))  # bottom, left, top, and right
  #par(mfrow=c(1, 1), mar=c(1, 0, 1, 2))
  
#plot(water, border = "#FFFFFF", col= "#FFFFFF", lwd=0.5,  cex= 0.75, main= "Top 1%") 

plot(europe,
     col = col_pal)

plot(land, border = "black", col= "#F8F9FA00", lwd=0.2, add=TRUE)
dev.off()

```


Let's do it with ggplot

```{r}

combined_plot_df <- combined %>% 
  mutate(hex_code = as.factor(hex_code),
         hex_code = ifelse(is.na(hex_code), "#FFFFFF", hex_code))

usa_bb <- st_as_sfc(st_bbox(c(
                    xmin = -8000000,
                    xmax = -6500000,
                    ymin = 5000000,
                    ymax = 6500000),
                    crs = gall_peters))

india_bb <- st_as_sfc(st_bbox(c(
                      xmin = 5200000,
                      xmax = 7500000,
                      ymin = 3000000,
                      ymax = 5000000),
                      crs = gall_peters))

europe_bb <- st_as_sfc(st_bbox(c(
                      xmin = -900000,
                      xmax = 900000,
                      ymin = 6500000,
                      ymax = 7500000),
                      crs = gall_peters))

global_map <- ggplot(combined) +
  geom_sf(data = land_for_ggplot, color = "black", fill = "transparent", size = 0.1) +
  geom_raster(aes(x = x, y = y, fill = hex_code)) +
  scale_fill_identity() +
  theme_void() +
  #theme(legend.position = "bottom") +
  geom_sf(data = usa_bb, aes(fill = "transparent"), linetype = "solid") +
  geom_sf(data = india_bb, aes(fill = "transparent"), linetype = "solid") +
  geom_sf(data = europe_bb, aes(fill = "transparent"), linetype = "solid") +
  theme(plot.margin = unit(c(0, 50, 0, 20), "pt")) 

global_map
```

Make map with insets on the map

-14207430, 14208570, -9000182, 8999818
```{r}

inset_maps <- ggdraw(global_map,
                     xlim = c(-0.2, 1.2),
                     ylim = c(-0.1, 1)) + 
  ## USA
  draw_plot(
    
    { global_map + coord_sf(xlim = c(-8000000, -6500000), ## -8000000, -6500000)
                            ylim = c(5000000, 6500000), expand=FALSE ) +  ## 5000000, 6500000
                            theme(legend.position = "none")},
    # The distance along a (0,1) x-axis to draw the left edge of the plot
    x = -0.2, 
    # The distance along a (0,1) y-axis to draw the bottom edge of the plot
    y = 0.2,
    # The width and height of the plot expressed as proportion of the entire ggdraw object
    width = 0.45, 
    height = 0.5) + 
  
  ## India
  draw_plot(
    { global_map + coord_sf(xlim = c(5200000, 7500000), ## 5000000, 7500000
                            ylim = c(3000000, 5000000), expand=FALSE )+ ## 3000000, 5000000
                            theme(legend.position = "none")},
    # The distance along a (0,1) x-axis to draw the left edge of the plot
    x = 0.82, 
    # The distance along a (0,1) y-axis to draw the bottom edge of the plot
    y = 0.3,
    # The width and height of the plot expressed as proportion of the entire ggdraw object
    width = 0.45, 
    height = 0.5) +

  
  ## Europe
  draw_plot(
    { global_map + coord_sf(xlim = c(-900000, 900000), ## 
                            ylim = c(6500000, 7500000), expand=FALSE )+ ## 
                            theme(legend.position = "none")},
    # The distance along a (0,1) x-axis to draw the left edge of the plot
    x = 0.4, 
    # The distance along a (0,1) y-axis to draw the bottom edge of the plot
    y = -0.1,
    # The width and height of the plot expressed as proportion of the entire ggdraw object
    width = 0.45, 
    height = 0.5) 

ggsave(here("_analysis/figures/paper/output/figure_3_overlap.png"), dpi = 300, width = 13.5, height= 8, units=c("in"))

```



