---
title: "Data check"
author: "Juliette"
date: "10/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(stringr)

source(here("_workflow/common.R"))
source(here("_workflow/common_spatial.R"))

```


Make a table with the global values for each category of the total space used

```{r}

disturbance_area_totals <- data_frame(animal = NA,
                                      system = NA,
                                      product = NA,
                                     km2 = NA)

files_list <- list.files(file.path(prep, "animal_farm/disturbance/total_area_rasters/"), pattern = ".tif", full.names = TRUE)

for(file in files_list) {
  
  # file <- files_list[1]
  
   animal_name <- str_split(str_split(file, pattern = "/")[[1]][13], pattern = "_")[[1]][1]
   system_name <- str_split(str_split(file, pattern = "/")[[1]][13], pattern = "_")[[1]][2]
   product_name <- str_split(str_split(file, pattern = "/")[[1]][13], pattern = "_")[[1]][3]
   
   raster <- raster(file) 
   
   km2_total <- cellStats(raster, 'sum') %>% 
     as_tibble() %>% 
     rename(km2 = value) %>% 
     mutate(animal = animal_name,
            system = system_name,
            product = product_name)
   
   
   disturbance_area_totals <- rbind(disturbance_area_totals, km2_total) %>% na.omit()
  
  write_csv(disturbance_area_totals, here("animal_farm/disturbance/plots/data_check/total_area_global_check.csv"))
  
}

```


Loop through making all the disturbance plots and save them


```{r}

files_list <- list.files(file.path(layers), pattern = "disturbance", full.names = TRUE)
files_list <-  str_subset(files_list, "land")

for(file in files_list) {
  
  # file <- files_list[1]
  
   animal_name <- str_split(str_split(file, pattern = "/")[[1]][9], pattern = "_")[[1]][2]
   system_name <- str_split(str_split(file, pattern = "/")[[1]][9], pattern = "_")[[1]][3]
   product_name <- str_split(str_split(file, pattern = "/")[[1]][9], pattern = "_")[[1]][4]
   
   rast <- raster(file)
   
   png(filename = here(paste0("animal_farm/disturbance/plots/data_check/", 
                              animal_name, "_", system_name, "_", product_name, "_disturbance.png")))
   plot(log(1 +rast),
        main = paste0(animal_name, " ", system_name, " ",  product_name, " logged disturbance"))
  
   dev.off()
 
  
}

```


