---
title: "comparing_parameters"
author: "Juliette"
date: "2/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyverse)
library(readr)
library(readxl)
library(stringr)

git_path <- '/home/verstaen/github/food_chicken_salmon'
```

```{r}
paper_para <- read_csv("data/salmon_parameters.csv") %>% 
  select(Parameter, Value)
```


```{r message = FALSE}
adc_comp_n <- read_delim("data/lex_input/adc_comp_n.csv", delim = ";")
adc_comp_p <- read_delim("data/lex_input/adc_comp_p.csv", delim = ";")
adc_noncomp_n <- read_delim("data/lex_input/adc_noncomp_n.csv", delim = ";")
adc_noncomp_p <- read_delim("data/lex_input/adc_noncomp_p.csv", delim = ";")
fcr_comp <- read_delim("data/lex_input/fcr_comp.csv", delim = ";")
frac_comp <- read_delim("data/lex_input/frac_comp.csv", delim = ";") %>% 
  filter(ISSCAAP_group == "Salmons, trouts, smelts")
frac_comp_n <- read_delim("data/lex_input/frac_comp_n.csv", delim = ";")
frac_comp_p <- read_delim("data/lex_input/frac_comp_p.csv", delim = ";")
```


adc_comp_n = 0.9
adc_comp_p = 0.6
adc_noncomp_n = 0.7
adc_noncomp_p = 0.45
fcr_comp = 1.25
frac_comp = 1
frac_comp_n = 0.07
frac_comp_p = 0.011









