---
title: "Untitled"
author: "Caitie"
date: "10/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(raster)
library(sf)

path<-"/home/shares/food-systems/Food_footprint/Data/Nutrient_pollution/"
```

# Norway region

```{r}
nor_reg<- st_read("/home/shares/food-systems/Food_footprint/Data/Country_regions/Norway/NO_Fylker_pol.shp")

nor_reg_latlon<-st_transform(nor_reg,crs = "+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0")
```


# Nutrient layers

```{r}
sed_p<-raster(paste0(path, "Salmon/sediment_P.asc"))

plot(sed_p)


```

```{r}
cellStats(sed_p,sum)
```

```{r}
sed_N<-raster(paste0(path, "Salmon/sediment_N.asc"))

plot(sed_N)
```

```{r}
cellStats(sed_N,sum)
```

```{r}
pp<-raster(paste0(path, "Salmon/PP.asc"))

plot(pp)
```

```{r}
cellStats(pp,sum)
cellStats(pp, mean)
cellStats(pp, max)
cellStats(pp, min)
```

```{r}
pp_crop<-crop(pp, nor_reg_latlon)
```

```{r}
plot(pp_crop)
```

```{r}
pp_removal<-raster(paste0(path, "Salmon/PP_removal.asc"))

plot(pp_removal)
```

```{r}
cellStats(pp_removal,sum)
```

```{r}
PN<-raster(paste0(path, "Salmon/PN.asc"))

plot(PN)
```

```{r}
cellStats(PN,sum)
cellStats(PN, mean)
cellStats(PN, max)
cellStats(PN, min)
```

```{r}
pn_crop<-crop(PN, nor_reg_latlon)
```

```{r}
plot(pn_crop)
```

```{r}
PN_removal<-raster(paste0(path, "Salmon/PN_removal.asc"))

plot(PN_removal)
```


```{r}
cellStats(PN_removal,sum)
```

```{r}
P_recycled<-raster(paste0(path, "Salmon/P_recycled.asc"))

plot(P_recycled)
```


```{r}
cellStats(P_recycled,sum)
```

```{r}
p_out<-raster(paste0(path, "Salmon/P_out.asc"))

plot(p_out)
```


```{r}
cellStats(p_out,sum)
cellStats(p_out, mean)
cellStats(p_out, max)
cellStats(p_out, min)
```

```{r}
p_out_crop<-crop(p_out, nor_reg_latlon)
```

```{r}
plot(p_out_crop)
```

```{r}
p_in<-raster(paste0(path, "Salmon/P_in.asc"))

plot(p_in)
```


```{r}
cellStats(p_in,sum)
cellStats(p_in, mean)
cellStats(p_in, max)
cellStats(p_in, min)
```

```{r}
p_in_crop<-crop(p_in, nor_reg_latlon)
```

```{r}
plot(p_in_crop)
```

```{r}
p_fish<-raster(paste0(path, "Salmon/P_fish.asc"))

plot(p_fish)
```


```{r}
cellStats(p_fish,sum)
```

```{r}
N_recycled<-raster(paste0(path, "Salmon/N_recycled.asc"))

plot(N_recycled)
```


```{r}
cellStats(N_recycled,sum)
```

```{r}
N_out<-raster(paste0(path, "Salmon/N_out.asc"))

plot(N_out)
```


```{r}
cellStats(N_out,sum)
cellStats(N_out, mean)
cellStats(N_out, max)
cellStats(N_out, min)
```

```{r}
n_out_crop<-crop(N_out, nor_reg_latlon)
```

```{r}
plot(n_out_crop)
```

```{r}
N_in<-raster(paste0(path, "Salmon/N_in.asc"))

plot(N_in)
```

```{r}
cellStats(N_in,sum)
cellStats(N_in, mean)
cellStats(N_in, max)
cellStats(N_in, min)
```

```{r}
n_in_crop<-crop(N_in, nor_reg_latlon)
```

```{r}
plot(n_in_crop)
```


```{r}
N_fish<-raster(paste0(path, "Salmon/N_fish.asc"))

plot(N_fish)
```

```{r}
cellStats(N_fish,sum)
```


```{r}
DP<-raster(paste0(path, "Salmon/DP.asc"))

plot(DP)
```

```{r}
cellStats(DP,sum)
cellStats(DP, mean)
cellStats(DP, max)
cellStats(DP, min)
```

```{r}
dp_crop<-crop(DP, nor_reg_latlon)
```

```{r}
plot(dp_crop)
```

```{r}
DP_removal<-raster(paste0(path, "Salmon/DP_removal.asc"))

plot(DP_removal)
```


```{r}
cellStats(DP_removal,sum)
```

```{r}
DN<-raster(paste0(path, "Salmon/DN.asc"))

plot(DN)
```

```{r}
cellStats(DN,sum)
cellStats(DN, mean)
cellStats(DN , max)
cellStats(DN, min)
```

```{r}
dn_crop<-crop(DN, nor_reg_latlon)
```

```{r}
plot(dn_crop)
```

```{r}
DN_removal<-raster(paste0(path, "Salmon/DN_removal.asc"))

plot(DN_removal)
```

```{r}
cellStats(DN_removal,sum)
```

