---
title: "Calculate protien and calories for freshwater fisheries catch"
author: "Juliette"
date: "3/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
source(here("_workflow/common.R"))
source(here("_workflow/common_spatial.R"))

'%!in%' <- function(x,y)!('%in%'(x,y))

```

Calculate an average for calories and protein for freshwater fisheries
```{r}
fresh_cal_pro <- read_csv(here("_efficiency/data/genus_compiled_fisheries.csv")) %>% 
  filter(GENuS_FoodName == "Freshwater Fish") %>% 
  group_by(GENuS_FoodName) %>% 
  dplyr::summarise(mean_calories = mean(Calories, na.rm = TRUE),
                   mean_protein = mean(Protein, na.rm = TRUE)) %>% 
  ungroup() %>% 
  mutate(kcal_per_tonne = mean_calories*1000,
         g_protein_per_tonne = mean_protein*1000)

kcal_per_tonne <- pull(fresh_cal_pro, kcal_per_tonne)
g_protein_per_tonne <- pull(fresh_cal_pro, g_protein_per_tonne)

```

Grab the total freshwater fish catch and calculate calories and mean

```{r}

fresh_fish <- read_csv(here("fisheries/freshwater/data/fw_catch_per_iso3c.csv")) %>% 
  select(-ID_0, - Country) %>% 
  rename(freshwater_tonnes = fw_catch_tonnes) 

```

Calculate an average from marine fishies for edibe weight
```{r}

prod_to_live_fish <- prod_to_live_fish_raw %>% 
  filter(is.na(presentation) | presentation == "whole") %>% 
  select(-'gutted, head off') %>% 
  rename(gutt_head_on = 'gutted, head on') %>% 
  dplyr::summarise(product_to_live_cf = mean(gutt_head_on, na.rm = TRUE)) %>% 
  mutate(live_to_edible = 1/product_to_live_cf)

edible_con <- pull(prod_to_live_fish, live_to_edible)

```



Calculate calories and protein
```{r}
fresh_fish_prot_cal <- fresh_fish %>% 
  mutate(kcal_total = kcal_per_tonne*edible_con*freshwater_tonnes,
         g_protein_total = g_protein_per_tonne*edible_con*freshwater_tonnes) 

write_csv(fresh_fish_prot_cal, here::here("_efficiency", "data", "freshwater_fisheries_protein_calories.csv"))  
  
```

