---
title: "ed_fig_2_production_maps.Rmd"
output: html_document
---

```{r}
library(tidyverse)
library(here)
library(stringr)
library(cowplot)
library(future)
library(furrr)
library(rnaturalearth)
library(scales)
library(rnaturalearthdata)
library(rgdal)
library(sp)
library(sf)
source(here("_workflow/common.R"))
source(here("_workflow/common_spatial.R"))
source(here("_analysis/figures/paper/colors_stressors_fig_1_2.R"))

predatalayers_path <- "/home/shares/food-systems/Food_footprint/all_food_systems/predatalayers/"
```

# Extract ls of tif paths
```{r}
production_tif_ls <- 
  list.files(predatalayers_path,
             pattern = "production|catch",
             full.names = TRUE)

## create a water raster
water <- readOGR(dsn = here("_analysis/raw/rgn_all_gcs_med_res.shp"))
water <- water[!water$rgn_nam == "Antarctica",]
proj4string(water) <- CRS("+proj=longlat +datum=WGS84 +no_defs")
water <- spTransform(water, CRS("+proj=longlat +datum=WGS84 +no_defs"))

## create a land raster
land <- ne_countries(scale = "medium", returnclass = "sp") 
land <- land[!land$sov_a3 == "ATA",]
land <- st_as_sf(land)
land <- st_transform(land, crs = food_crs)
land <- as(land, "Spatial")
```

# Plotting
```{r}

png_save <- function(production_path) { 

  # Extract files with specific crop
  production_raster <- raster(production_path)
  
  png(here(sprintf("_analysis/figures/extended_data/output/ed_fig_2_production_png/%s.png", 
                   str_extract(production_path, pattern = "(?<=predatalayers\\/\\/).*(production|catch)"))),
      res=200, width=18, height=10, units="in")
  
  par(oma = c(0,0,0,4), mar=c(0, 0, 0, 2))  
  
  plot(water, border= "#FFFFFF", col="#FFFFFF", lwd=1.5)
  
  plot(production_raster,
       col = dist_palette,
       legend.width=1,
       axis.args = list(cex=2, cex.axis = 2),    
       add = TRUE)
  
  plot(land, border = "#BCBEB1", col= "#F8F9FA00", lwd=0.8, add=TRUE)
  
  dev.off()
  
}
```

# Map function
```{r}
plan(multisession, workers = 12)
options <- furrr_options(seed = 54232)
future_map(production_tif_ls, png_save,
           .options = options)
```
