---
title: "fig_SX_data_quality_assessment_wrangling.Rmd"
output: html_document
---

# Preamble
```{r}
library(here)
source(here("_workflow/common.R"))
source(here("_workflow/common_spatial.R"))
source(here("_spatial/template_raster.R"))
library(janitor)
library(data.table)
library(stringr)
```

# System and pressure combos

```{r}
pressures <- c("Nutrient", "GHG", "Water", "Disturbance")

file_list <- 
  list.files(layers,
           full.names = FALSE) %>% 
  .[!grepl(pattern = "_x_", .)]

crop_rows <- 
  tibble(pressure = pressures,
         system = rep("crop", 4),
         origin = rep("land", 4),
         product = rep("produce", 4),
         organism = rep("food_crop"))

marine_cf_rows <-
  tibble(pressure = pressures,
         system = rep("fisheries", 4),
         origin = rep("marine", 4),
         product = rep("meat", 4),
         organism = rep("fish", 4))

marine_aquaculture_rows <-
  tibble(pressure = pressures,
         system = rep("aquaculture", 4),
         origin = rep("marine", 4),
         product = rep("meat", 4),
         organism = rep("mariculture", 4))

fodd_rows <- 
  crop_rows %>% 
  mutate(organism = "fodd")

stressor_combo <- 
  read.table(text = sub("\\.tif$", "", file_list), sep = "_") %>% 
  rename(origin = V1, organism = V2, system = V3, product = V4, pressure = V5) %>% 
  filter(!system %in% "crop" & !origin %in% "marine") %>% 
  bind_rows(fodd_rows,
            crop_rows,
            marine_cf_rows,
            marine_aquaculture_rows)

stressor_combo_farmed_meat <- 
  stressor_combo %>% 
  filter(!system %in% c("fisheries", "crop")) %>% 
  expand_grid(., 
              farm_feed = c("feed", "farm")) %>% 
  mutate(pressure = if_else(farm_feed == "feed",
                            NA_character_,
                            pressure)) %>% 
  unique()
  
stressor_combo2 <- 
  stressor_combo %>% 
  filter(system %in% c("fisheries", "crop")) %>% 
  mutate(farm_feed = "farm") %>% 
  bind_rows(stressor_combo_farmed_meat)

write_csv(stressor_combo2,
          here("_analysis/figures/SI/data/system_stressor_combination.csv"))
```
 


```{r}


test_different_food_system_options <- function(food_systems_opt) {
  
  spatial_resolution_scores <- c(sample(x=c(1, 3, 5), size = length(food_systems_opt) * 4, replace=TRUE))
  spatial_extent_scores     <- c(sample(x=c(1, 3, 5), size = length(food_systems_opt) * 4, replace=TRUE))
  temporal_accuracy_scores  <- c(sample(x=c(1, 3, 5), size = length(food_systems_opt) * 4, replace=TRUE))
  system_specificity_scores  <- c(sample(x=c(1, 3, 5), size = length(food_systems_opt) * 4, replace=TRUE))
  
  dummy_score_df <-
    expand_grid(food_system = food_systems_opt, pressures_short) %>%
    add_column(spatial_extent_scores,
               spatial_resolution_scores,
               temporal_accuracy_scores,
               system_specificity_scores) %>%
    mutate(average_score =
             (spatial_extent_scores +
              spatial_resolution_scores +
              temporal_accuracy_scores + 
              system_specificity_scores) / 4)
  
  # order_criteria <-
  #   c("Spatial Resolution", "Spatial Cover", "Temporal Accuracy", "Overall Score")
  #
  # order_food_systems <- c(dummy_score_df$average_score)
  
  # GGPlot
  
  dummy_score_food_systems <-
    dummy_score_df %>%
    unique() %>%
    unite(food_system, 1:2, sep = ": ") %>%
    pivot_longer(cols      = 2:6,
                 names_to  = "criteria",
                 values_to = "score")
  
  ### Heatmap!
  
  ggplot(dummy_score_food_systems,
         aes(x = criteria, y = food_system)) +
    geom_tile(aes(fill = score)) +
    scale_fill_gradient2(midpoint = 3,
                         low = "darkred", mid = "orange", high = "darkgreen", na.value = "grey80",
                         breaks = c(1.5 ,3, 4.5),
                         labels = c("Bad","Medium", "Good")) +
    theme_dark() +
    ggtitle("Pressure Data Selection Criteria Scores") +
    theme(axis.text.x     = element_text(angle = 45, hjust = 1),
          axis.title      = element_blank(),
          panel.grid      = element_blank(),
          legend.title    = element_blank(),
          legend.position = "bottom") +
    coord_cartesian(expand = FALSE)
  
  # Mel's idea for averaging score
  
  dummy_score_alt <- 
    dummy_score_df %>% 
    select(food_system, pressures_short, average_score)
  
  ggplot(dummy_score_alt,
         aes(x = pressures_short, y = food_system)) +
    geom_tile(aes(fill = average_score)) +
    scale_fill_gradient2(midpoint = 3,
                         low = "darkred", mid = "orange", high = "darkgreen", na.value = "grey80",
                         breaks = c(1.5 ,3, 4.5),
                         labels = c("Bad","Medium", "Good")) +
    theme_dark() +
    ggtitle("Food system by Pressure Data Selection Criteria Scores") +
    theme(axis.text.x     = element_text(angle = 45, hjust = 1),
          axis.title      = element_blank(),
          panel.grid      = element_blank(),
          legend.title    = element_blank(),
          legend.position = "bottom") +
    coord_cartesian(expand = FALSE)
  
  ## when saving make sure to save it tall enough so that there's no over lap for the yaxis labels
  # ggsave(here("_analysis/figures/SI/output/fig_SX_data_quality_assessment.jpg"), 
  #        width=10, height=8, dpi=300)
  
}

lapply(list_food_systems, test_different_food_system_options)
```
