---
title: "Exploring FAO aquaculture data"
output: html_document
editor_options: 
  chunk_output_type: console
---

This script filters and classifies the FAO aquaculture data to match the 6 species groups we are including in our marine analysis (tuna, salmon, shrimp, bivalve, general finfish, and crustaceans). 

```{r}
library(tidyverse)
library(here)
library(countrycode)

source(here('aquaculture/R/fao_mar_clean.R')) # functions specific to mariculture dealing with compound countries
source('https://raw.githubusercontent.com/OHI-Science/ohiprep_v2019/gh-pages/workflow/R/fao_fxn.R') # function for cleaning FAO files

```

```{r}

fao <- read_csv("/home/shares/food-systems/Food_footprint/_raw_data/FAO_aquaculture/v_2020/FAO_GlobalAquacultureProduction_Quantity_1950_2018.csv")

fao <- fao %>%
  rename(country = `Country (Country)`,
         species = `ASFIS species (ASFIS species)`, 
         fao_major_area = `FAO major fishing area (FAO major fishing area)`, 
         environment = `Environment (Environment)`) %>%
  dplyr::select(-Unit)
table(fao$environment)  
## convert to long format and clean FAO codes:
fao <- fao %>%
  gather(key="year", value="value", -country, -species, -fao_major_area, -environment) %>%
    fao_clean_data() %>%
  filter(year >= 2010) %>%
  group_by(country, species, fao_major_area, environment) %>%
  mutate(total_harvest = sum(value, na.rm=TRUE)) %>%
  filter(total_harvest > 0) %>% # data is cut if country/species/major area hasn't been harvested since 2010
  dplyr::select(-total_harvest) %>%
  ungroup()

## convert to iso3c codes
fao <- fao %>% 
  filter(!country == "Totals") %>%  ## filter out "totals" rows
  filter(!is.na(species)) %>%  ## filter out "totals" rows
  mutate(country = ifelse(country == "R\xe9union", "Reunion", country)) %>%
  filter(!country %in% c("Yugoslavia SFR", "Un. Sov. Soc. Rep.")) %>%  # these countries no longer exist  
  mutate(country = ifelse(country=='Zanzibar', "Tanzania", country)) %>%  #semiautonomous region of Tanzania
  mutate(country = ifelse(country=="Eswatini", "Swaziland", country)) %>%  # also goes by this name
  mar_split() %>%   # fixes channel islands, breaks into Guernsey and Jersey
  mutate(iso3c = countrycode(country, "country.name", "iso3c"))
## make sure no NAs:
table(fao$iso3c)
## save
write.csv(fao, here("aquaculture/data/fao_mariculture_clean.csv"), row.names=FALSE)


```


## explore freshwater
```{r}

fao <- read_csv("aquaculture/data/fao_mariculture_clean.csv")

fw <- fao %>%
  dplyr::filter(environment == "Freshwater") %>%
  group_by(species) %>%
  summarize(total = sum(value)) %>%
  ungroup() %>%
  arrange(total)

data.frame(fw)

write.csv(fw, "aquaculture/marine/STEP1_species_groups/int/fw_spp.csv", row.names = FALSE)


```


## explore marine
```{r}

marine <- fao %>%
  filter(environment %in% c("Marine", "Brackishwater")) %>%
  group_by(species) %>%
  summarize(total = sum(value)) %>%
  ungroup() %>%
  arrange(total)

data.frame(marine)

## 323 different species

# emissions <- read_csv("aquaculture/data/emissions_aquaculture.csv")
# unique(emissions$`Scientific Name`)
## 32 different species 


fao_marine <- fao %>%
  filter(environment %in% c("Marine", "Brackishwater"))

  

## Read in list of species from OHI so that we can add higher taxonomic classifications
mar_sp_list <- read_csv("https://raw.githubusercontent.com/OHI-Science/ohiprep_v2020/gh-pages/globalprep/mar/v2020/raw/species_list.csv")

fao_marine_fw_not_included <- fao_marine %>%
  left_join(mar_sp_list, by = c("species" = "FAO_name")) %>%
  dplyr::select(-exclude, -alias) %>%
  dplyr::filter(str_detect(species, "Freshwater|catfish|Cyprinids|ilapia|iver")) 


fao_marine_clean <- fao_marine %>%
  left_join(mar_sp_list, by = c("species" = "FAO_name")) %>%
  dplyr::select(-exclude, -alias) %>%
  dplyr::filter(!str_detect(species, "Freshwater|catfish|Cyprinids|ilapia|iver"),
                Taxon_code != "AL",
                species != "Red oyas",
                species != "Jellyfishes nei") ## delete freshwater, catfish species, seaweeds, jellyfish..
```

Classify species into aquaculture groups 
```{r}
# Need to classify into these groups: 
#  - Bivalves
#  - Tuna
#  - Salmonids
#  - Shrimps and Prawns
#  - crustaceans
#  - marine fish general

## Make a dataframe of each unique species to hand check what category they should fall into
check <- fao_marine_clean %>%
  distinct(species, Taxon_code)

##  Salmonids : "It includes salmon, trout, chars, freshwater whitefishes, and graylings, which collectively are known as the salmonids."
## Safe to classify trout in the same category as salmon: "Farmed steelhead trout also is rainbow trout, but it is farmed in saltwater netpens in the same manner as Atlantic salmon in countries"
## Safe to classify Char in same category as salmon.
## Octopus : use offshore floating sea cages for production and fed bycatch - lump with marine fish - general
## All of those classified as BI will be Bivalves
## CRUST - classified as bivalves
## GAST - classify as bivalves
## sea cucumber - classify as bivalve
## Sandfish == sea cucumber = bivalve
## Tunicates - Use longlines as aquaculture practice - Oysters also use longline - classify these as bivalves 
## Urchins - classify as bivalve
## SH classified as Shrimp
## crabs and lobsters classified as crustaceans

## filter for salmon, char, trout and reclassify to aquaculture group = salmonids
salmon_list <- fao_marine_clean %>%
  dplyr::filter(str_detect(species, "almon|char|rout|European whitefish")) %>% ## filter for salmon, trout, and char
  dplyr::mutate(aq_group = "salmonids")

## filter for Taxon_codes GAST, INV, CRUST, TUN, URCH, NS-INV (sea cucumbers/sandfish), BI  and reclassify to aquaculture group = bivalves
bivalve_list <- fao_marine_clean %>%
  dplyr::filter(Taxon_code %in% c("TUN", "URCH", "NS-INV", "BI", "GAST", "INV")) %>% ## filter for tunicates, urchins, invertebrates, bivalves and gastropods
  dplyr::mutate(aq_group = "bivalves")

## filter for Taxon_code == SH and classify as aquaculture group shrimps_prawns
shrimps_list <- fao_marine_clean %>%
  dplyr::filter(Taxon_code == "SH"|
                str_detect(species, "Metapenaeus shrimps nei")) %>%
  dplyr::mutate(aq_group = "shrimps_prawns")

crustacean_list <- fao_marine_clean %>%
  dplyr::filter(Taxon_code == "CRUST") %>%
  dplyr::mutate(aq_group = "crustaceans")

tuna_list <- fao_marine_clean %>%
  dplyr::filter(str_detect(species, "tuna")) %>%
  dplyr::mutate(aq_group = "tuna")

## Filter out all other lists and classify the rest as marine_fish
marine_fish_list <- fao_marine_clean %>%
  dplyr::filter(species %notin% c(shrimps_list$species, bivalve_list$species, salmon_list$species, crustacean_list$species, tuna_list$species)) %>%
  dplyr::mutate(aq_group = "marine_fish_general")

## combine them all together again 
aquaculture_groups <- rbind(salmon_list, bivalve_list, shrimps_list, marine_fish_list, crustacean_list, tuna_list)

## write it out
write.csv(aquaculture_groups, "aquaculture/marine/STEP1_species_groups/int/marine_groups.csv", row.names = FALSE)


aq_groups <- read.csv("aquaculture/marine/STEP1_species_groups/int/marine_groups.csv")


fao_1 <- read.csv(here("aquaculture/data/fao_mariculture_clean.csv")) %>%
  filter(environment %in% c("Marine", "Brackishwater")) %>%
  left_join(aq_groups) %>%
  dplyr::filter(year == 2017,
                !is.na(value),
                !is.na(aq_group)) %>%
  dplyr::filter(value >= 500) %>%
  group_by(aq_group, country, species, year) %>%
  summarise(tonnes = sum(value)) %>%
  ungroup() %>%
  # dplyr::filter(tonnes >= 500) %>%
  group_by(country, aq_group, year) %>%
  summarise(total_tonnes = sum(tonnes)) %>%
  arrange(aq_group)

write.csv(fao_1, "aquaculture/marine/STEP1_species_groups/int/tonnes_per_country_group.csv", row.names = FALSE)


test <- fao_1 %>%
  dplyr::filter(aq_group == "bivalves")
sum(test$total_tonnes) # 17439040

test <- fao_1 %>%
  dplyr::filter(aq_group == "shrimps_prawns")
sum(test$total_tonnes) # 5094133

```

