---
title: "Relationship between production and farm size"
output: html_document
editor_options: 
  chunk_output_type: console
---

Some of the salmon farm data is based on polygons.  I am going to explore these data to see if we can find some general relationhip between salmon production and area.  This would be for the occupancy/disturbance data.


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(raster)
library(tidyverse)
library(stringr)
library(rgdal)
library(PBSmapping)
library(maptools)
library(sf)
library(lwgeom)
library(data.table)
library(here)

path <- "/home/shares/food-systems/Food_footprint/_raw_data/Aquaculture_locations"

```

## Get fao production and regional production values
```{r}

fao <- read_csv(here("salmon_farm/data/fao_mariculture_salmon.csv")) %>%
  dplyr::filter(year == 2016)

subregion <- read.csv(here("salmon_farm/data/proportional_regional_production.csv")) %>%
  dplyr::select(region, prop_production)
```


### Chile data
```{r}

chile_dat <- st_read(file.path(path, "Chile"), layer = "Concesiones_de_Acuicultura")
#Filter to only salmon farming
chile <- chile_dat %>% 
  filter(grepl("SALMON", REP_SUB_13)) %>%
  dplyr::select(region = REP_SUB_20, geometry)

chile$area <- st_area(chile)

## standardize names
chile_sub <- data.frame(region =c("REGIÓN DE ATACAMA", "REGIÓN DE AYSÉN DEL GENERAL CARLOS IBÁÑEZ DEL CAMPO",
                                       "REGIÓN DE COQUIMBO", "REGIÓN DE LA ARAUCANÍA", "REGIÓN DE LOS LAGOS",
                                       "REGIÓN DE LOS RÍOS", "REGIÓN DE MAGALLANES Y DE LA ANTÁRTICA CHILENA",
                                       "REGIÓN DE ÑUBLE", "REGIÓN DEL BIOBÍO", "REGIÓN DEL MAULE"),
                        new_name = c("Atacama", "Aisén del General Carlos Ibáñez del Campo",
                                     "Coquimbo", "Araucanía", "Los Lagos", "Los Ríos", 
                                     "Magallanes y Antártica Chilena", "Bío-Bío", "Bío-Bío", "Maule"))

chile <- chile %>%
  left_join(chile_sub, by="region") %>%
  dplyr::select(region=new_name, area) %>%
  group_by(region) %>%
  summarize(area = sum(area)) %>%
  ungroup()
  
chile <- chile %>%
  mutate(iso3c = "CHL") %>%
  left_join(fao) %>%
  left_join(subregion, by="region") %>%
  mutate(production = fao_tonnes_production*prop_production)

chile_production <- data.frame(area = chile$area, production = chile$production, iso3c="CHL")


```

## Canada

```{r}
## BC
bc <- st_read(file.path(path, "Canada/CRIMS_S_WATER_FINFISH_TENURES/WAT_FNF_TN_polygon.shp"))

bc$area <- st_area(bc)
bc_production <- data.frame(area = sum(bc$area),
                            production = 123522*6.562107e-01,
                            iso3c="CAN")


## NB
nb <- st_read(file.path(path,"/Canada/New_brunswick_Finfish_mol.shp"))

nb$area <- st_area(nb)
nb_production <- data.frame(area = sum(nb$area),
                            production = 123522*1.651790e-01,
                            iso3c="CAN")


## NS
ns <- st_read(file.path(path,"Canada/Nova_Scotia_Marine_Aquaculture_Sites/geo_export_fcc6f2ef-82bb-4445-98f0-a82a56cd0d00.shp"))
# id salmon
salmon <- grep("Salmon|salmon", unique(ns$aqua_speci), value=TRUE)

ns <- ns %>%
  filter(aqua_speci %in% salmon)

ns <- st_transform(ns_salmon, crs = "+init=epsg:3035") # convert to equal area projection to find centroids. 
ns$area <- st_area(ns)
ns_production <- data.frame(area = sum(ns$area),
                            production = 123522*3.960878e-02,
                            iso3c="CAN")

```



## US
```{r}
## NE
us_ne <- st_read(file.path(path,"USA/NE/US_NE_Aquaculture.shp"))


# id salmon and active sites
salmon_species <- grep("Salmon|salmon", unique(us_ne$allSpecies), value=TRUE)

us_ne <- us_ne %>%
  filter(allSpecies %in% salmon_species) %>%
  filter(status == "Active")

us_ne <- st_transform(us_ne_salmon, crs = "+init=epsg:3035") # convert to equal area projection to find centroids. 

us_ne$area <- st_area(us_ne)
us_ne_production <- data.frame(area = sum(us_ne$area),
                            production = 16185-7711,    
                            iso3c="USA") # subtracting estimate of production in PS


```


## Ireland
```{r}
ireland <- st_read(file.path(path,"Ireland/AquacultureLicenceGISData23122019/Aqua_Sites_Redacted_23-12-2019.shp"))

ire <- ireland %>%
  dplyr::filter(Species_Na %in% "Salmon")

ire$area <- st_area(ire_salmon)

ire_production <- data.frame(area = sum(ire$area),
                            production = 16300,
                            iso3c="IRL") # includes PS and NE production


```


# Combine and analyze

```{r}

all <- rbind(chile_production, ns_production, nb_production, bc_production, us_ne_production, ire_production)
plot(all$area[all$production > 0], all$production[all$production > 0])

all <- all %>%
  group_by(iso3c) %>%
  summarize(area = sum(area),
            production = sum(production)) %>%
  mutate(m2_per_tonne = area/production)
  



```
