---
title: "Fisheries data check"
author: "Gage Clawson (UCSB, NCEAS, OHI)"
date: "September 25, 2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

### Check that the data seems reasonable.
From Parker paper: 
 - Estimated 81 million tons of landings in 2011.  

v5 Watson:
  IYear tonnes_all tonnes_IND tonnes_NIND
1  2015  108990539   89507297    19483243
2  2016  108547470   88871350    19676120
3  2017  111226186   91071850    20154336

v4 Watson; the folder in aurora indicates v3, but it is actually v4 from 2019, I checked): 
 - If including non-industrial, 100 million tonnes in 2011 (excluding discards).  
 - If only using industrial, 65 million tonnes in 2011 (excluding discards). 
 
Their data (most likely) (v3 Watson) 
 - If including non-industrial, 115 million in 2011 (excluding discards). 
 - If only using industrial, 86 million in 2011 (excluding discards).

So does Parker include non-industrial? 
 - In their paper they account for non-motorized vessel type. This indicates to me that they did include non-industrial in their estimates. 
 - They also include a note that fishery LCAs have primarily been done on industrial fishing activities... implying their estimates might be slightly off for rates of emissions, meaning that non-industrial is included. 
 - HOWEVER, the numbers (seen above), indicate otherwise... 
 - I am going to do it both ways... save a raster with just industrial and one with both. I think Parker 2018 uses just industrial based off of the numbers we are seeing. 

Calculate total catch:
```{r}
total_reported_catch_v5 <- read_csv(file.path(raw_folder_watson, "Catch2015_2019.csv")) %>%
  mutate(total_catch = ReportedIND + IUUIND + ReportedNIND + IUUNIND,
         IND_catch = ReportedIND + IUUIND,
         NIND_catch =  ReportedNIND + IUUNIND) %>%
  group_by(IYear) %>%
  summarize(tonnes_all = sum(total_catch, na.rm=TRUE),
            tonnes_IND = sum(IND_catch, na.rm = TRUE), 
            tonnes_NIND = sum(NIND_catch, na.rm = TRUE))
data.frame(total_reported_catch_v5)

#   IYear tonnes_all tonnes_IND tonnes_NIND
# 1  2015  108990539   89507297    19483243
# 2  2016  108547470   88871350    19676120
# 3  2017  111226186   91071850    20154336

total_reported_catch_v3 <- read_csv(file.path(raw_folder, "watson_data/v3.0/Index_v3.csv")) %>%
  mutate(total_catch = IndReported + IndIUU + NIndReported + NIndIUU) %>%
  group_by(Year) %>%
  summarize(tonnes_all = sum(total_catch, na.rm=TRUE))

v3_2011 <- total_reported_catch_v3 %>%
  filter(Year == 2011) # 115252616 includes non-industrial

total_reported_catch_v3_ind <- read_csv("/home/shares/food-systems/Food_footprint/_raw_data/watson_data/v3.0/IndexInd.csv") %>%
  mutate(total_catch = IndReported + IndIUU) %>%
  group_by(Year) %>%
  summarize(tonnes_all = sum(total_catch, na.rm=TRUE))

v3_2011_ind <- total_reported_catch_v3_ind %>%
  filter(Year == 2011) # 86548897

total_reported_catch_ind <- read_csv("/home/shares/food-systems/Food_footprint/_raw_data/watson_data/v3.0/IndexInd.csv") %>%
  mutate(total_catch = Reported + IUUTotal + Discards) %>%
  group_by(IYear) %>%
  summarize(tonnes_all = sum(total_catch, na.rm=TRUE))

total_reported_catch_Nind <- read_csv("/home/shares/food-systems/Food_footprint/_raw_data/watson_data/v3.0/IndexNInd.csv") %>%
  mutate(total_catch = Reported + IUUTotal + Discards) %>%
  group_by(IYear) %>%
  summarize(tonnes_all = sum(total_catch, na.rm=TRUE))

ind_2011 <- total_reported_catch_ind %>%
  filter(IYear == 2011) #73048009
Nind_2011 <- total_reported_catch_Nind %>%
  filter(IYear == 2011) #36507858

# 109555867... ~30 mil larger... What about excluding discards? 


total_reported_catch_ind <- read_csv("/home/shares/food-systems/Food_footprint/_raw_data/watson_data/v3.0/IndexInd.csv") %>%
  mutate(total_catch = Reported + IUUTotal) %>%
  group_by(IYear) %>%
  summarize(tonnes_all = sum(total_catch, na.rm=TRUE))

total_reported_catch_Nind <- read_csv("/home/shares/food-systems/Food_footprint/_raw_data/watson_data/v3.0/IndexNInd.csv") %>%
  mutate(total_catch = Reported + IUUTotal) %>%
  group_by(IYear) %>%
  summarize(tonnes_all = sum(total_catch, na.rm=TRUE))

ind_2011 <- total_reported_catch_ind %>%
  filter(IYear == 2011) #65466334
Nind_2011 <- total_reported_catch_Nind %>%
  filter(IYear == 2011) #35400517

# 100866851... ~20 mil larger... when excluding discards 



```