---
title: "land, ocean, coastal rasters"
author: "Juliette"
date: "1/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)

source(here("_workflow/common.R"))
source(here("_workflow/common_spatial.R"))

land_raw <- raster(file.path(prep, "spatial/gall_peters/food_rgns_gall_peters.tif"))
plot(land_raw)
summary(land_raw)

eez_raw <- raster(file.path(prep, "spatial/gall_peters/eez_rgns_gall_peters.tif"))
plot(eez_raw)
summary(eez_raw)

```

New rasters 
```{r}

land <- calc(land_raw, fun=function(x){ifelse(x > 0, 1, 0)})
land <- calc(land, fun=function(x){ifelse(is.na(x), 0, x)})
plot(land)

eez <- calc(eez_raw, fun=function(x){ifelse(x >0, 1, 0)})
eez <- calc(eez, fun=function(x){ifelse(is.na(x), 0, x)})
plot(eez)

coastal <- sum(land, eez, na.rm = TRUE)
coastal <- calc(coastal, fun=function(x){ifelse(x == 2, 1, 0)})
plot(coastal)

land <- land-coastal
eez <- eez - coastal

## grab the total cummulative impact final layer
chi <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/stressor_summary/equal_area/rescaled/cumulative_stress/all_systems_cumulative_stress.tif")

## quantile 99
quant <- quantile(chi, 0.99)

top_1_per <- calc(chi, fun=function(x){ifelse(x >= quant, 1, 0)})
plot(top_1_per)

#what is the sum of all the cells that are in the top 1%
cellStats(top_1_per, stat = 'sum', na.rm = TRUE) ##142080

# number of cells in top 1% on land
land_calc <- sum(land, top_1_per, na.rm = TRUE)
plot(land_calc)
land_calc <- calc(land_calc, fun=function(x){ifelse(x == 2, 1, 0)})
cellStats(land_calc, stat = 'sum') ## 141029
141029/142080 ## 0.9926028

# number of cells in top 1% on coastal
coast_calc <- sum(coastal, top_1_per, na.rm = TRUE)
plot(coast_calc)
coast_calc <- calc(coast_calc, fun=function(x){ifelse(x == 2, 1, 0)})
cellStats(coast_calc, stat = 'sum') ## 189
189/142080 ## 0.001330236


# number of cells in top 1% on eez
eez_calc <- eez + top_1_per
eez_calc <- calc(eez_calc, fun=function(x){ifelse(x == 2, 1, 0)})
cellStats(eez_calc, stat = 'sum') ## 838
838/142080 #  0.005898086

## 142056, we are missing 23 cells. maybe this difference isn't too big a deal? only reason i can think of is that these cells of impact are happening in freshwater systems that the rgns layer does not capture? although were not doing lakes...

```


