---
title: Global map of dominant pressure
output: html_document
---

```{r setup, include=FALSE}
library(rgdal)
library(sp)
library(sf)
library(raster)
library(tidyverse)
library(here)
library(rnaturalearth)
library(scales)
library(rnaturalearthdata)

source(here("_workflow/common.R"))
source(here("_workflow/common_spatial.R"))
```

water and land prep
```{r}
## save the gall peters projection
gall_peters <- "+proj=cea +lon_0=0 +x_0=0 +y_0=0 +lat_ts=45 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"

## create a water raster
water <- readOGR(dsn = here("_analysis/raw/rgn_all_gcs_med_res.shp"))
water <- water[!water$rgn_nam == "Antarctica",]
proj4string(water) <- CRS("+proj=longlat +datum=WGS84")
water <- spTransform(water, CRS("+proj=cea +lon_0=0 +x_0=0 +y_0=0 +lat_ts=45 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"))

## create a land raster
land <- ne_countries(scale = "medium", returnclass = "sp") 
land <- land[!land$sov_a3 == "ATA",]
land <- st_as_sf(land)
land <- st_transform(land, crs = gall_peters)
land <- as(land, "Spatial")
```

Plot of dominant pressure

```{r}
pressure_stack <- stack(list.files("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/stressor_summary/equal_area/rescaled/stressors", full=TRUE))

pressure_df <- as.data.frame(pressure_stack, xy = TRUE)

pressure_df_total <- 
  pressure_df %>%
  rowwise() %>% 
  mutate(total = sum(c(disturbance, ghg, nutrient, water), na.rm=TRUE))

pressure_df_prop <-
  pressure_df_total %>%
  rowwise() %>% 
  mutate(disturbance_prop = disturbance / total,
         ghg_prop         = ghg / total,
         nutrient_prop    = nutrient / total,
         water_prop       = water / total)

pressure_df_prop[8:11][is.na(pressure_df_prop[8:11])] <- 0

# The following method does not have a solution for when there are two or more
# pressure have the same (highest) proportion. 

pressure_df_prop_dominant_pressure <- 
  pressure_df_prop[8:11] %>%
  rowwise() %>% 
  mutate(dominant_pressure = names(.)[which.max(c_across(everything()))])

dominant_pressure_df <- 
  bind_cols(pressure_df_prop, pressure_df_prop_dominant_pressure[5])

dominant_pressure_df <- 
  dominant_pressure_df %>% 
  mutate(dominant_pressure = ifelse(total == 0, 
                                     NA, 
                                     dominant_pressure))

counts <- table(dominant_pressure_df$dominant_pressure)

counts * 36 / 1000000 / 510.1

round((counts * 36 / 509984343) * 100, 2)

n_global_cells <- 14208000

dominant_pressure_df_xy <- 
  dominant_pressure_df %>%
  dplyr::select(x, y, dominant_pressure)

# prop of global
prop <- 
  dominant_pressure_df_xy %>% 
  as_tibble() %>% 
  mutate(dominant_pressure = if_else(dominant_pressure == "no_pressure", 0, 1)) %>% 
  summarise(sum = sum(dominant_pressure, na.rm = TRUE)) %>% 
  mutate(prop = sum / n_global_cells) %>% 
  pull(prop) # 0.883

dominant_pressure_df_xy_ordinal <- 
  dominant_pressure_df_xy %>%
    as_tibble() %>% 
    mutate(dominant_pressure = case_when(
      dominant_pressure == "disturbance_prop" ~ 1,
      dominant_pressure == "ghg_prop" ~ 2,
      dominant_pressure == "nutrient_prop" ~ 3,
      dominant_pressure == "water_prop" ~ 4
    ))

dominant_pressure_raster <- 
  rasterFromXYZ(dominant_pressure_df_xy_ordinal,
                crs = gall_peters)
plot(dominant_pressure_raster)

# writeRaster(dominant_pressure_raster,
#             "/home/shares/food-systems/Food_footprint/all_food_systems/_analysis/figures/SI/output/dominant_pressure_no_threshold.tif", overwrite = TRUE)

# red, green, orange, blue
#color_pal <- c("#aa7828", "#c996a9", "#305E5A", "#97c9ca")
#color_pal <- c('#ac2e48','#31634a', '#d76934', '#052a91')
# color_pal <- c('#9d4158','#5b9d45', '#ce642ac9', '#4254ad58')
# color_pal <- c('#a6611a','#80cdc1', '#dfc27d', '#018571')
# color_pal <- c('#2c7bb6','#abd9e9', '#fdae61', '#d7191c')
#disturbance, ghg, nutrient, water
#color_pal <- c('#d5bd75', '#da6098', '#795b48', '#77c1d7')
#dist, ghg, water, nut 
color_pal <- c("#D5BD75", "#DA6098", "#795B48", "#3E638E")
scales::show_col(color_pal)
## save the map
png(here("_analysis/figures/SI/output/fig_S5_majority_map.png"), res=500, width=7, height=3, units="in")

par(oma=c(1,1,1,0), new = TRUE) # bottom, left, top, and right
par(mfrow=c(1, 1), mar=c(1, 0, 1, 2))

plot(water, border= "#F8F9FA", col="#F8F9FA", lwd=0.5, main=sprintf("Majority pressure", system), cex=0.75)
plot(land, border="#BCBEB1", col="#F8F9FA", lwd=0.2, add=TRUE)
plot(dominant_pressure_raster, col=c(color_pal[1], color_pal[2], color_pal[3], color_pal[4]), add=TRUE)
#plot(land, lwd=0.2, add=TRUE)
dev.off()

counts_df <- data.frame(counts)
counts_df$pressure <- c("disturbance", "ghg", "nutrient", "water")
counts_df$plot_color <- color_pal
mytheme <- 
  theme(axis.line=element_blank(),
        axis.text.x=element_text(angle=50,hjust=1, size = rel(3)),
        axis.text.y=element_blank(),axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),legend.position="none",
        panel.background=element_blank(),panel.border=element_blank(),panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),plot.background=element_blank())
p <- ggplot(counts_df, aes(y=Freq, x= reorder(pressure, -Freq), fill=color_pal)) +
  geom_bar(stat="identity", width=1) +
  scale_fill_identity() +
  mytheme 
#  theme_void()
  
ggsave(p, filename = "_analysis/figures/SI/output/fig_S5_legend.png",  bg = "transparent", width = 3, height = 4)
```