---
title: "fig_SX_food_treemap"
output: html_document
---

# Preamble
```{r}
library(here)
source(here("_workflow/common.R"))
source(here("_workflow/common_spatial.R"))
source(here("_spatial/template_raster.R"))
library(janitor)
library(data.table)
library(stringr)
library(googledrive)
library(googlesheets4)
library(cowplot)
library(treemap)
library(vroom)
```


```{r}
treemap_df <- 
  vroom(here("_analysis/figures/SI/data/SI_treemap_df.csv"), 
            .name_repair = make_clean_names) %>% 
  separate(food_category, c("food_category", "subcategory"), sep = "(:|,)") %>% 
  mutate(subcategory = str_remove(subcategory, "\\d")) %>% 
  filter(included_tonnes_1e6 != 0) %>% 
  mutate(subcategory = str_replace(subcategory, "^\\s", "")) %>% 
  mutate(subcategory = Hmisc::capitalize(subcategory))
```

# Number of foods per category
```{r}
crop_codes <- vroom(here("crop/farm/data/crop_codes_updated.csv"))

crop_codes_joining <- 
  crop_codes %>% 
  select(split_rest_names, SPAM_super) %>% 
  unique()

SPAM_super_prod <- 
  vroom(here("crop/farm/data/prod_crop_rgns_2017.csv")) %>% 
  filter(prod_system == "A") %>% 
  group_by(split_rest_names) %>% 
  summarise(included_tonnes_1e6 = sum(production, na.rm = TRUE)) %>% 
  ungroup() %>% 
  left_join(crop_codes_joining) %>% 
  group_by(subcategory = SPAM_super) %>% 
  summarise(included_tonnes_1e6 = sum(included_tonnes_1e6, na.rm = TRUE) / 1000000) %>% 
  ungroup() %>% 
  filter(!subcategory %in% c("ofib", "toba", "teas", "xcof")) 

crop_cats <- 
  crop_codes %>% 
  count(subcategory = SPAM_super) %>% 
  filter(!subcategory %in% c("ofib", "toba", "teas", "xcof"))

SPAM_df <- 
  SPAM_super_prod %>% 
  mutate(food_category = "Crops",
         subcategory = Hmisc::capitalize(subcategory))

mari_cats <- 
  vroom("/home/shares/food-systems/Food_footprint/all_food_systems/dataprep/aquaculture/marine/production_for_juliette.csv") %>%
  select(subcategory = aq_group, species) %>% 
  unique() %>% 
  group_by(subcategory) %>% 
  count() %>% 
  ungroup() 

catch_cats <- 
  read_csv("/home/shares/food-systems/Food_footprint/all_food_systems/dataprep/fisheries/marine/catch_for_juliette.csv") %>%  
  select(TaxonName, subcategory = species_class_final) %>%
  unique() %>% 
  group_by(subcategory) %>% 
  count() %>% 
  ungroup()
```

# Aquatic food

```{r}
treemap_mariculture_df <- 
  vroom(here("_analysis/figures/SI/data/SI_treemap_aquatic.csv"), 
             .name_repair = make_clean_names) %>% 
  mutate(food_category = "Mariculture",
         subcategory = "Animals",
         included_tonnes_1e6 = production_tonnes / 1000000) %>% 
  select(-c(production_tonnes, taxa_examples))

treemap_marine_fish_df <- 
  vroom(here("_analysis/figures/SI/data/SI_treemap_marine_fisheries.csv"), 
             .name_repair = make_clean_names)[-1,] %>%
  select(-c(catch_tonnes_reported_iuu, description)) %>% 
  mutate(food_category = "Marine fisheries",
         subcategory = if_else(classification == "Fish oil / fish meal",
                               "Fish oil and fish meal taxa",
                               "Excluding fish oil and fish meal taxa"),
         included_tonnes_1e6 = parse_number(catch_tonnes) / 1000000) %>% 
  rename(class = classification) %>% 
  select(-catch_tonnes)

treemap_aquatic_df <- 
  treemap_df %>% 
  filter(food_category == "Freshwater fisheries") %>% 
  select(1:3) %>% 
  bind_rows(treemap_mariculture_df,
            treemap_marine_fish_df) %>% 
  select(-subcategory) %>% 
  rename(subcategory = class)
```

# bind together
```{r}
food_cat_n <- 
  bind_rows(mari_cats, catch_cats, crop_cats) %>% 
  mutate(subcategory = Hmisc::capitalize(subcategory)) %>% 
  mutate(subcategory = str_replace_all(subcategory, "_", " ")) %>% 
  mutate(subcategory = case_when(
    subcategory == "Small pelagic" ~ "Small pelagics",
    subcategory == "Medium pelagic" ~ "Medium pelagics",
    subcategory == "Large pelagic" ~ "Large pelagics",
    subcategory == "Marine fish general" ~ "General marine fish",
    subcategory == "Shrimps prawns" ~ "Shrimp",
    subcategory == "Bivalves" ~ "Unfed or algae fed shellfish",
    subcategory == "Forage fish" ~ "Fish oil / fish meal",
     subcategory == "Crustaceans" ~ "Other crustaceans",
    TRUE ~ subcategory
  ))

treemap_df_2 <- 
  treemap_df %>% 
  select(-c(produced_tonnes_1e6, percent_included1)) %>% 
  filter(!food_category %in% c("Crops", "Marine fisheries", "Mariculture", "Freshwater fisheries")) %>% 
  bind_rows(treemap_aquatic_df) %>%
  bind_rows(SPAM_df) %>% 
  left_join(food_cat_n) %>% 
  rename(food_cats_number = n) %>% 
  mutate(food_cats_number = case_when(
    food_category == "Livestock" & subcategory == "Meat" ~ 5,
    food_category == "Livestock" & subcategory == "Milk" ~ 4,
    food_category == "Livestock" & subcategory == "Eggs" ~ 1,
    TRUE ~ as.numeric(food_cats_number))) %>% 
  mutate(food_cats_number = paste("n", as.character(food_cats_number), sep = " = "))
```


```{r}
treemap_df_3 <- 
  treemap_df_2 %>% 
  mutate(subcategory = case_when(
    subcategory == "Sugc" ~ "Sugarcane",
    subcategory == "Maiz" ~ "Maize",
    subcategory == "Vege" ~ "Vegetables",
    subcategory == "Whea" ~ "Wheat",
    subcategory == "Xfru" ~ "Fruit",
    subcategory == "Sugb" ~ "Sugarbeet",
    subcategory == "Cass" ~ "Cassava",
    subcategory == "Pota" ~ "Potato",
    subcategory == "Oilp" ~ "Oilpalm",
    subcategory == "Barl" ~ "Barley",
    subcategory == "Xoil" ~ "Oilcrop",
    subcategory == "Xpul" ~ "Pulses",
    subcategory == "Ocer" ~ "Other cereals",
    subcategory == "Soyb" ~ "Soybean",
    subcategory == "Bana" ~ "Banana",
    subcategory == "Swpo" ~ "Sweet potato",
    subcategory == "Cnut" ~ "Coconut",
    subcategory == "Xmil" ~ "Millet",
    subcategory == "Plnt" ~ "Plantain",
    subcategory == "Tnut" ~ "Treenuts",
    subcategory == "Sorg" ~ "Sorghum",
    subcategory == "Orts" ~ "Other roots",
    TRUE ~ subcategory
  ))


# Custom labels:
treemap(treemap_df_3, 
        index=c("food_category","subcategory", "food_cats_number"),     
        vSize="included_tonnes_1e6", type="index",
        fontsize.labels=c(30, 16, 14),                # size of labels. Give the size per level of aggregation: size for group, size for subgroup, sub-subgroups...
        title = "",
        fontcolor.labels=c("white","white", "white"),    # Color of labels
        fontface.labels=c(2, 2, 3),                  # Font of labels: 1,2,3,4 for normal, bold, italic, bold-italic...
        bg.labels=c("transparent"),              # Background color of labels
        align.labels=list(
            c("left", "top"), 
            c("center", "center"),
            c("right", "bottom")
            ),                                   # Where to place labels in the rectangle?
        overlap.labels=0,                      # number between 0 and 1 that determines the tolerance of the overlap between labels. 0 means that labels of lower levels are not printed if higher level labels overlap, 1  means that labels are always printed. In-between values, for instance the default value .5, means that lower level labels are printed if other labels do not overlap with more than .5  times their area size.
        inflate.labels=F,                        # If true, labels are bigger when rectangle is bigger.
        border.col=c("black","white"),             # Color of borders of groups, of subgroups, of subsubgroups ....
        border.lwds=c(2,2),                         # Width of colors
        palette = c("#43EA57", # green
                    "#17B9FF", # blue
                    "#FF6800", # red
                    "#D9EB23", # yellow
                    "#17B9FF") # blue
        
    )


```

```{r}
treemap_aquatic_df2 <- 
  treemap_aquatic_df %>% 
  left_join(food_cat_n) %>% 
  mutate(n = paste("n", as.character(n), sep = " = "))


# Custom labels:
treemap_plot <- 
  treemap(treemap_aquatic_df2, 
          index=c("food_category", "subcategory", "n"),     
          vSize="included_tonnes_1e6", 
          title = "",
          type="index",
          fontsize.labels=c(30,16, 14),                # size of labels. Give the size per level of aggregation: size for group, size for subgroup, sub-subgroups...
          fontcolor.labels=c("white", "white", "white"),    # Color of labels
          fontface.labels=c(2, 2, 3),                  # Font of labels: 1,2,3,4 for normal, bold, italic, bold-italic...
          bg.labels = "transparent",              # Background color of labels
          align.labels=list(
              c("left", "top"), 
              c("center", "center"),
              c("right", "bottom")
              ),                                   # Where to place labels in the rectangle?
          overlap.labels=0,                      # number between 0 and 1 that determines the tolerance of the overlap between labels. 0 means that labels of lower levels are not printed if higher level labels overlap, 1  means that labels are always printed. In-between values, for instance the default value .5, means that lower level labels are printed if other labels do not overlap with more than .5  times their area size.
          inflate.labels=F,                        # If true, labels are bigger when rectangle is bigger.
          border.col=c("black","white"),             # Color of borders of groups, of subgroups, of subsubgroups ....
          border.lwds=c(2,2),                         # Width of colors
          palette = c("#17B9FF", #blue
                      "#D9EB23")     #yellow                   # Select your color palette from the RColorBrewer presets or make your own.
        
    )
 
```

# Livestock

```{r}
global_prod_treemap <- 
  global_prod %>% 
  rename(animal_pro = 'Animal-Product') %>% 
  mutate(included = ifelse(str_detect(animal_pro, "cow|cattle|chicken|hen|goat|sheep|buffalo|pig"), "included", "not included"),
         included = ifelse(animal_pro == "buffalo-meat", "not included", included)) 


livestock_treemap_df <- 
  vroom(here("_analysis/figures/SI/data/global_prod_treemap.csv")) %>% 
  filter(included == "included") %>% 
  separate(animal_pro, c("animal", "product"), sep = "-") %>% 
  mutate(animal = Hmisc::capitalize(animal),
         product = Hmisc::capitalize(product)) %>% 
  mutate(animal = if_else(animal == "Hen", 
                          "Chicken",
                          animal))

treemap_plot <- 
  treemap(livestock_treemap_df, 
          index= c("product", "animal"),     
          vSize="Tonnes", 
          title = "",
          type="index",
          fontsize.labels=c(30,18),                # size of labels. Give the size per level of aggregation: size for group, size for subgroup, sub-subgroups...
          fontcolor.labels=c("white", "white"),    # Color of labels
          fontface.labels=c(2,2),                  # Font of labels: 1,2,3,4 for normal, bold, italic, bold-italic...
          bg.labels = "transparent",              # Background color of labels
          align.labels=list(
              c("left", "top"), 
              c("center", "center")
              ),                                   # Where to place labels in the rectangle?
          overlap.labels=0,                      # number between 0 and 1 that determines the tolerance of the overlap between labels. 0 means that labels of lower levels are not printed if higher level labels overlap, 1  means that labels are always printed. In-between values, for instance the default value .5, means that lower level labels are printed if other labels do not overlap with more than .5  times their area size.
          inflate.labels=F,                        # If true, labels are bigger when rectangle is bigger.
          border.col=c("black","white"),             # Color of borders of groups, of subgroups, of subsubgroups ....
          border.lwds=c(2,1),                         # Width of colors
          palette = "#FF6800"                        # Select your color palette from the RColorBrewer presets or make your own.
        
    )
```

# summary stats
```{r}

  treemap_df %>% 
  select(-c(produced_tonnes_1e6, percent_included1)) %>% 
  filter(!food_category %in% c("Crops", "Marine fisheries", "Mariculture", "Freshwater fisheries")) %>% 
  bind_rows(treemap_aquatic_df) %>%
  bind_rows(SPAM_df) %>% 
  left_join(food_cat_n) %>% 
  rename(food_cats_number = n) %>% 
  mutate(food_cats_number = case_when(
    food_category == "Livestock" & subcategory == "Meat" ~ 5,
    food_category == "Livestock" & subcategory == "Milk" ~ 4,
    food_category == "Livestock" & subcategory == "Eggs" ~ 1,
    TRUE ~ as.numeric(food_cats_number)))  %>% 
  group_by(food_category) %>% 
  summarise(total_categories = sum(food_cats_number, na.rm = TRUE)) %>% 
  ungroup()

```

