---
title: "Chicken count correction"
output: html_document
editor_options: 
  chunk_output_type: console
---

This estimates the proportion of backyard vs. industrial chickens.

```{r setup, include=FALSE}

library(here)
library(sp)
library(raster)
library(tidyverse)
library(countrycode)

source(here("_workflow/common.R"))

```


FAO livestock headcounts.  We used the manure data because it breaks production into layers and broilers.
```{r}

fao <- read_csv(file.path(raw, "FAO_data/v2020/FAO_livestock_head_count_2020_09_25.csv")) %>%
  filter(Area != "China") %>%
  mutate(Area = ifelse(Area == "Netherlands Antilles (former)", "Bonaire, Sint Eustatius and Saba", Area))

fao$iso3c <- countrycode(as.character(fao$Area), origin="country.name", destination = "iso3c")
filter(fao, is.na(fao$iso3c))

fao_chickens <- filter(fao, Item %in% c("Chickens, broilers", "Chickens, layers")) %>%
  filter(Element=="Stocks") %>%
  select(iso3c, fao_manure_count = Value) %>%
  group_by(iso3c) %>%
  summarize(fao_manure_count = sum(fao_manure_count, na.rm=TRUE))

```

Our mapped counts

```{r}

chickens_ind_meat <-
    vroom::vroom("/home/shares/food-systems/Food_footprint/all_food_systems/dataprep/animal_farm/farm/chickens_industrial_meat_location_df.csv", 
    col_select = c(x, y, contains("current"), iso3c)) %>% 
    rename(current_count = 3)
chickens_ind_eggs <-
    vroom::vroom("/home/shares/food-systems/Food_footprint/all_food_systems/dataprep/animal_farm/farm/chickens_industrial_eggs_location_df.csv", 
    col_select = c(x, y, contains("current"), iso3c)) %>% 
    rename(current_count = 3)
chickens_by <-
    vroom::vroom("/home/shares/food-systems/Food_footprint/all_food_systems/dataprep/animal_farm/farm/chickens_backyard_eggs&meat_location_df.csv", 
    col_select = c(x, y, contains("current"), iso3c)) %>% 
    rename(current_count = 3)

#rbind(chickens_ind_eggs, chickens_ind_meat)%>% group_by(iso3c) %>% summarize(mapped_count = sum(map_head_count, na.rm=TRUE)) %>% data.frame()
#chickens_by %>% group_by(iso3c) %>% summarize(mapped_count = sum(map_head_count, na.rm=TRUE)) %>% data.frame()

chickens_industrial <- rbind(chickens_ind_eggs, chickens_ind_meat) %>%
  group_by(iso3c) %>%
  summarize(ind_chickens = sum(current_count, na.rm=TRUE))

chickens_by_iso <- chickens_by %>%
  group_by(iso3c) %>%
  summarize(by_chickens = sum(current_count, na.rm=TRUE))

all_chickens <- rbind(chickens_ind_eggs, chickens_ind_meat, chickens_by) %>%
  group_by(iso3c) %>%
  summarize(our_count_all = sum(current_count, na.rm=TRUE)) %>%
  left_join(chickens_by_iso) %>%
  left_join(chickens_industrial) %>%
  left_join(fao_chickens) %>%
  arrange(-our_count_all) %>%
  mutate(prop_by = by_chickens/fao_manure_count) %>%
  data.frame() %>%
  ungroup()

# fill in the weird ones
all_chickens_fill <- all_chickens %>%
  rowwise() %>%
  mutate(prop_by2 = ifelse(our_count_all == 0, 0, prop_by)) %>%
  mutate(prop_by2 = ifelse(is.na(fao_manure_count) & is.na(prop_by2), (by_chickens/our_count_all), prop_by2)) %>%
  mutate(prop_by2 = ifelse(prop_by2 > 1, (by_chickens/our_count_all), prop_by2))

summary(all_chickens_fill)
filter(all_chickens_fill, prop_by>1)

all_chickens_fill %>% arrange(-prop_by2)


## final data
industrial_correct <- all_chickens_fill %>%
mutate(industrial_correct = 1 - prop_by2) %>%
  select(iso3c, industrial_correct) %>%
  filter(!is.na(iso3c))
summary(industrial_correct)

write_csv(industrial_correct, here("animal_farm/farm/data/industrial_chicken_correct.csv"))
```