---
title: "Rescaling rasters"
output: html_document
editor_options: 
  chunk_output_type: console
---

We rescale each food raster (equal area per cell values) by the global total of the corresponding global total of stressor.  We multiply by 1e6 to avoid very small values.  

Run time: 1 hour
```{r setup, include=FALSE}
library(rgdal)
library(sp)
library(raster)
library(tidyverse)
library(here)
```

```{r}
rescaling_data <- read_csv(here("_analysis/rescale_values.csv"))

pressure_list <- c("ghg", "nutrient", "disturbance", "water")

for(stressor in pressure_list){ # stressor = "nutrient"
  
  resc_num <- rescaling_data$global_total[rescaling_data$pressure==stressor] 
  
stressor_system_files <- list.files("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/_tif_equal_area_proj_per_cell", pattern=stressor, full=TRUE)
  

  for(stressor_raster_filename in stressor_system_files){ #stressor_raster_filename= stressor_system_files[1]
file_name <- basename(stressor_raster_filename)
file_name <- gsub("_per_cell.tif", "", file_name)
file_name <- paste0(file_name, "_rescaled.tif")

stressor_raster <- raster(stressor_raster_filename)
rescaled_raster = raster::calc(stressor_raster, fun=function(x){ifelse(x>0, 
                                      (x/resc_num) * 1000000, 
                                       0)})
writeRaster(rescaled_raster, sprintf("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/_tif_equal_area_proj_per_cell_rescaled/%s", file_name),
              overwrite=TRUE)
}
}

aux_files <- list.files("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/_tif_equal_area_proj_per_cell_rescaled", full=TRUE, pattern = ".aux.xml")
file.remove(aux_files)

```

