---
title: "Paper Stats using production data"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

library(ggplot2)
library(tidyverse)
library(here)
library(countrycode)
library(cowplot)

source(here("_workflow/common.R"))

```

Get production data for each group.

### Livestock
```{r, eval = FALSE}
## Livestock animal products
livestock_cats <- read_csv(here("_analysis/paper_stats/data/FAO_livestock_categories.csv")) %>%
  filter(!is.na(category1_production))
table(livestock_cats$category1_production)
table(livestock_cats$category2_production)

livestock <- read_csv(here("_analysis/paper_stats/data/FAOSTAT_data_12-18-2020_livestock_primary.csv")) %>%
  filter(Area != "China") %>%
  filter(!(is.na(Value))) %>%
  filter(Item %in% livestock_cats$Item) %>%
  left_join(livestock_cats, by="Item") %>%
  group_by(Area, category1_production, category2_production) %>%
  summarize(tonnes = sum(Value)) %>%
  ungroup()

livestock_iso3c <- livestock %>%
    mutate(Area = iconv(Area, "UTF-8", "UTF-8",sub=''),
         Area = ifelse(Area == "Eswatini", "Swaziland", Area),
         Area = ifelse(Area == "Netherlands Antilles (former)", "Bonaire, Sint Eustatius and Saba", Area),
         Area = ifelse(Area == "French Guyana", "French Guiana", Area),
         Area = ifelse(Area == "China, mainland", "China", Area))

## add standardized country names
livestock_iso3c$iso3c<- countrycode(as.character(livestock_iso3c$Area), origin="country.name", destination = "iso3c")

## make sure all countries have an iso3c code
check <- filter(livestock_iso3c, is.na(iso3c))
unique(check$Area) # these are all higher level area, safe to delete NAs

livestock_iso3c <- livestock_iso3c %>%
  select(iso3c, category1_production, category2_production, tonnes)

```

### Marine fisheries

```{r, eval = FALSE}

# marine_fish_old <- read_csv("/home/shares/food-systems/Food_footprint/all_food_systems/dataprep/fisheries/marine/catch_by_rgn_spp_class.csv") %>%
#   mutate(category1_production = recode(species_class, "Benthic" = "benthic_meat",
#              "Demersal" = "demersal_meat",
#              "forage_fish" = "fofm_meat",
#              "Large pelagic" = "large-pelagic_meat",
#              "Medium pelagic" = "medium-pelagic_meat",
#              "Reef-associated" = "reef_meat",
#              "Small pelagic" = "small-pelagic_meat")) %>%
# #  group_by(country_corrected, iso3c) %>%
# #  summarize(tonnes = sum(catch_tonnes, na.rm=TRUE)) %>%
#   mutate(category2_production = "marine_fisheries") %>%
#   select(iso3c, category1_production, category2_production, tonnes=catch_tonnes)


marine_fish <- read_csv("/home/shares/food-systems/Food_footprint/all_food_systems/dataprep/fisheries/marine/catch_extracted_final.csv") %>%
  mutate(category1_production = recode(species_class_final, "Benthic" = "benthic_meat",
             "Demersal" = "demersal_meat",
             "forage_fish" = "fofm_meat",
             "Large pelagic" = "large-pelagic_meat",
             "Medium pelagic" = "medium-pelagic_meat",
             "Reef-associated" = "reef_meat",
             "Small pelagic" = "small-pelagic_meat")) %>%
#  group_by(country_corrected, iso3c) %>%
#  summarize(tonnes = sum(catch_tonnes, na.rm=TRUE)) %>%
  mutate(category2_production = "marine_fisheries") %>%
  select(iso3c, category1_production, category2_production, tonnes=catch) %>%
  filter(tonnes > 0)
```

### Crops for humans
```{r, eval = FALSE}
fao_prod <- read_csv(here("feed/data/MAPSPAMcrop_production.csv"))
human_crop_prop <- read_csv("feed/data/human_crop_prop_consume.csv")

crop_tonnes <- left_join(human_crop_prop, fao_prod, by=c("iso3c_producing", "SPAM_super")) %>%
  rowwise() %>%
  mutate(tonnes = human_feed_prop*tonnes_producing_crop) %>%
  #group_by(iso3c_producing) %>%
  #summarize(tonnes = sum(tonnes, na.rm=TRUE)) %>%
  mutate(category2_production = "human_crop") %>%
  mutate(category1_production = paste(SPAM_super, "produce", sep = "_")) %>%
  select(iso3c = iso3c_producing, category1_production, category2_production, tonnes)

```


### Mariculture: 
```{r, eval = FALSE}

# mariculture_old <- read_csv(here("aquaculture/marine/STEP1_species_groups/int/tonnes_per_country_group.csv")) %>%
#  # filter(!(aq_group %in% "bivalves")) %>%
#   mutate(aq_group = ifelse(aq_group=="marine_fish_general", "marine-fish-general", aq_group),
#          aq_group = ifelse(aq_group=="salmonids", "salmon", aq_group),
#          aq_group = ifelse(aq_group=="shrimps_prawns", "shrimp", aq_group)) %>%
#   select(country, species = aq_group, tonnes=total_tonnes) %>%
#   mutate(iso3c = countrycode(country, origin="country.name", destination = "iso3c")) %>%
#   mutate(category1_production = paste(species, "_meat", sep = ""),
#          category2_production = "mariculture") %>%
#   select(-country, -species)


mariculture <- read_csv(file.path("/home/shares/food-systems/Food_footprint/all_food_systems/dataprep/aquaculture/marine/production_extracted_final.csv")) %>%
 # filter(!(aq_group %in% "bivalves")) %>%
  mutate(aq_group = ifelse(aq_group=="marine_fish_general", "marine-fish-general", aq_group)) %>%
  select(Country, iso3c, species = aq_group, tonnes=total_tonnes) %>% 
  mutate(category1_production = paste(species, "_meat", sep = ""),
         category2_production = "mariculture") %>% 
  select(-Country, -species) %>%
  filter(tonnes > 0)

```


### Feed: Crops
```{r, eval = FALSE}

livestock_cats <- read_csv(here("_analysis/paper_stats/data/raster_livestock_cats.csv"))
table(livestock_cats$category2_production, livestock_cats$category1_production)

mapspam_feed <- read_csv(here("feed/data/tonnes_feedproduced_per_country_system.csv")) %>% left_join(livestock_cats, by="animal_system") %>%
  filter(!(is.na(category2_production))) %>%
    mutate(feed_source = "crops") %>%
  group_by(iso3c_producing, feed_source, category1_production, category2_production) %>%
  summarize(tonnes = sum(consumed_tonnes, na.rm=TRUE)) %>%
  dplyr::select(iso3c=iso3c_producing, category1_production, category2_production, feed_source, tonnes) %>%
  ungroup() 


```

### Feed: fodder

```{r, eval = FALSE}

# # remove old files in folder that are created here
# do.call(file.remove, list(list.files("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/fodder_tonnes", full.names = TRUE)))
# 
# fodder_prod <- sum(stack(raster(file.path(prep, "crop/farm/scaled_maps_2017/crop_fodd_I_scaled.tif")), raster(file.path(prep, "crop/farm/scaled_maps_2017/crop_fodd_H_scaled.tif"))), na.rm=TRUE)
# 
# fodder_props <- list.files("/home/shares/food-systems/Food_footprint/all_food_systems/datalayers", pattern="_x_land_fodd", full=TRUE)
# 
# for(fodder_prop in fodder_props){ #fodder_prop = fodder_props[1]
#   fodder_raster <- raster(fodder_prop)
#   saveName <- basename(fodder_prop)
#   saveName <- gsub("_x_land_fodd_crop_feed", "", saveName)
#   saveName <- gsub("_land_", "", saveName)
#   fodder_tonnes <- fodder_raster * fodder_prod
#   writeRaster(fodder_tonnes, sprintf("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/fodder_tonnes/%s", saveName), overwrite=TRUE)
# }

fodd_tonnes_stack <- stack(list.files("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/fodder_tonnes", full=TRUE))

rgns_eez_land <- raster(file.path(prep, "spatial/land_eez_rgns.tif"))
plot(rgns_eez_land)

country_sum <- zonal(fodd_tonnes_stack, rgns_eez_land, fun="sum", progress="text", na.rm=TRUE) %>% 
    data.frame() %>%
    rename(ID_0 = zone) %>%
    left_join(food_rgns, by="ID_0") %>%
    select(-ID_0)

country_fodder <- country_sum %>%
   pivot_longer(cols=c(-Country, -iso3c), "animal_system") %>%
   mutate(animal_system = gsub("^land_", "", animal_system)) %>%
     mutate(animal_system = gsub("eggs.meat", "eggs&meat", animal_system)) %>%
   left_join(livestock_cats, by="animal_system") %>%
  mutate(feed_source = "fodder") %>%
  select(iso3c, category1_production, category2_production, feed_source, tonnes=value)

```

Feed: FOFM

```{r, eval = FALSE}
fofm <- read_csv(here("feed/data/FMFO_bySource_2021Apr.csv")) %>%
  mutate(feed_source = "feedfofm") %>%
  rename(animal_system = system) %>%
  left_join(livestock_cats, by="animal_system") %>%
  filter(!is.na(category2_production)) %>%
  select(iso3c, category1_production, category2_production, feed_source, tonnes) %>% 
  group_by(iso3c, category1_production, category2_production, feed_source) %>% 
  dplyr::summarise(tonnes = sum(tonnes))

```

# Calculate total tonnes of feed per country for each animal group:
```{r, eval = FALSE}

total_feed <- rbind(country_fodder, fofm, mapspam_feed) %>%
  group_by(iso3c, category1_production, category2_production) %>%
  summarize(tonnes = sum(tonnes, na.rm=TRUE)) %>%
  mutate(category1_production = paste("feed_", category1_production, sep="")) %>%
  mutate(category2_production = paste("feed_", category2_production, sep="")) %>%
  filter(category1_production != "feed_NA")

```


Freshwater fish: 
```{r, eval = FALSE}
fresh_fish <- read_csv(here("fisheries/freshwater/data/fw_catch_per_iso3c.csv")) %>% 
  select(-ID_0, - Country) %>% 
  rename(tonnes = fw_catch_tonnes) %>% 
  mutate(category1_production  = "fish_meat",
         category2_production = "freshwater_fisheries")

setdiff(food_rgns$iso3c, fresh_fish$iso3c)
setdiff(fresh_fish$iso3c, food_rgns$iso3c)
```

## Join products
```{r, eval = FALSE}

product_tonnes <- rbind(livestock_iso3c, marine_fish, crop_tonnes, fresh_fish, mariculture, total_feed)

## deal with feed backyard chickens
product_tonnes_feed_chickens <- product_tonnes %>%
  filter(category1_production == "feed_chickens_backyard_eggs&meat") %>%
  mutate(tonnes = tonnes/2) 

product_tonnes_feed_chickens_eggs <- product_tonnes_feed_chickens %>%
  mutate(category1_production = "chickens_eggs")
product_tonnes_feed_chickens_meat <- product_tonnes_feed_chickens %>%
  mutate(category1_production = "chickens_meat")

product_tonnes <- product_tonnes %>%
  filter(category1_production != "feed_chickens_backyard_eggs&meat") %>% 
  rbind(product_tonnes_feed_chickens_eggs, product_tonnes_feed_chickens_meat) %>% 
  mutate(category1_production = ifelse(category1_production == "bivalves_meat", "bivalve_meat", category1_production))

write.csv(product_tonnes, "_analysis/paper_stats/output/all_production.csv", row.names = FALSE)


check_new <- product_tonnes %>%
  group_by(category2_production) %>%
  summarise(sum = sum(tonnes))



```


#### Get global proportions of production

## now lets do everything - what we will use in figure 4

```{r, eval = FALSE}
product_tonnes_total <- product_tonnes %>%
  group_by(iso3c) %>%
  summarise(country_tonnes = sum(tonnes, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(total_prod = sum(country_tonnes, na.rm = TRUE)) %>%
  mutate(prop_prod = country_tonnes/total_prod)


sum(product_tonnes_total$prop_prod) # 1 - perfect

write.csv(product_tonnes_total, "_analysis/paper_stats/output/all_production_props.csv", row.names = FALSE)

test <- read_csv("_analysis/paper_stats/output/all_production_props.csv")


```


