---
title: "proportion animal contribution to cpi"
output: html_document
editor_options: 
  chunk_output_type: console
---

Calculate the proportion of each animal/product to cumulative pressure.
```{r setup, include=FALSE}

library(rgdal)
library(sp)
library(sf)
library(raster)
library(tidyverse)
library(here)
library(rnaturalearth)
library(rnaturalearthdata)

## save the gall peters projection
gall_peters <- "+proj=cea +lon_0=0 +x_0=0 +y_0=0 +lat_ts=45 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"

```

Read in files and divide by cpi:
```{r}

system_files <- list.files("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/cpi", full=TRUE)

for(system_file in system_files){ # system_file = system_files[1]
  
  system_raster <- raster(system_file)
  cpi <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/stressor_summary/equal_area/rescaled/cumulative_stress/all_systems_cumulative_stress.tif")
  save_name <- basename(system_file)
  
  system_prop <- system_raster/cpi
  #plot(system_prop)
  writeRaster(system_prop, sprintf("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi/prop_cpi_%s", save_name), overwrite=TRUE)
}

  ## doing some of these at higher level:

## delete files for individuals, and then create/save other file
combined_animals <- list.files("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi", full=TRUE)
combined_animals <- grep("sheep|goats|chickens|cows", combined_animals, value=TRUE)
do.call(file.remove, list(combined_animals))

## chickens
sum_raster <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/cpi/chickens_meat.tif") + 
  raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/cpi/chickens_eggs.tif") + raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/cpi/chickens_eggs&meat.tif")

prop_raster <- sum_raster/cpi
  writeRaster(prop_raster, "/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi/prop_cpi_chickens_eggs&meat.tif", overwrite=TRUE)

  ## shoats
  sum_raster <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/cpi/goats_meat.tif") +
  raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/cpi/goats_milk.tif") +
  raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/cpi/sheep_milk.tif") +
    raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/cpi/sheep_meat.tif")
  #plot(prop_raster)
  
  prop_raster <- sum_raster/cpi

  writeRaster(prop_raster, "/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi/prop_cpi_shoats_meat&milk.tif", overwrite=TRUE)

  ## cows
  sum_raster <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/cpi/cows_meat.tif") +
  raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/cpi/cows_milk.tif")
  
  prop_raster <- sum_raster/cpi
  
    writeRaster(prop_raster, "/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi/prop_cpi_cows_meat&milk.tif", overwrite=TRUE)
```


## make a figure identifying dominant food
first step is to make rasters when raster exceeds a threshold. 

```{r}

# function to ID thresholds
threshold_food <- function(threshold){ # threshold = 0.50
prop_files <- list.files("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi", full=TRUE)

for(file in prop_files){  # file = prop_files[7]
  
  raster_name <- basename(file)
  prop_raster <- raster(file)
  prop_raster[prop_raster >= threshold] <- 1
  prop_raster[prop_raster < threshold] <- NA
  #plot(prop_raster)
  writeRaster(prop_raster, sprintf("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh%s_%s", threshold*100, raster_name), overwrite=TRUE)

}

}


threshold_food(threshold = 0.50)
threshold_food(threshold = 0.80)


## data frame of dominant food 

dom_food_list <- list.files("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold", full=TRUE)

dom_food_list_df <- data.frame()

for(dom_food in dom_food_list){ #dom_food <- dom_food_list[1]
  tmp_name <- basename(dom_food)
  tmp <- raster(dom_food)
  tmp_data <- cellStats(tmp, "sum", na.rm=TRUE)  
  tmp_df <- data.frame(raster = tmp_name, total_cells = tmp_data)
  dom_food_list_df <- rbind(dom_food_list_df, tmp_df)
}
```

CPI exploration
```{r}
library(gt)

land <- ne_countries(scale = "medium", returnclass = "sp") 
land <- land[!land$sov_a3 == "ATA",]
land <- st_as_sf(land)
land <- st_transform(land, crs=gall_peters)
land <- as(land, "Spatial")

cpi <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/stressor_summary/equal_area/rescaled/cumulative_stress/all_systems_cumulative_stress.tif")
#plot(log(cpi+1))
no_prop <- calc(cpi, fun = function(x){ifelse(x > 0.001, 1, 0)})

png(here(sprintf("_analysis/figures/paper/output/fig_3_explore_thresh.png", system)), res=500, width=7, height=3, units="in")

par(oma=c(1,1,1,0), new = TRUE) # bottom, left, top, and right
par(mfrow=c(1, 1), mar=c(1, 0, 1, 2))
plot(no_prop, col = c("#FFFFFF", "#ADB2AC")) ## looks right!
plot(land, lwd= 0.5, add = TRUE)

dev.off()

cpi_2 <- calc(cpi, fun = function(x){ifelse(x == 0, NA, x)})

quantile_values <- c(0.99, 0.95, 0.9, 0.8, 0.7, 0.5, 0.2, 0.15, 0.1, 0.05, 0.01, 0.005, 0.001, 0.0001)
quants <- quantile(cpi_2, quantile_values)
quant_table <- as_tibble(quants) %>% 
  mutate(quantile = quantile_values) %>% 
  gt()

## look at quant 0.9[3], 0.8 [4] and 0.7[5]
no_prop <- calc(cpi, fun = function(x){ifelse(x > quants[6], 1, 0)})

png(here(sprintf("_analysis/figures/paper/output/fig_3_explore_thresh_05.png", system)), res=500, width=7, height=3, units="in")

par(oma=c(1,1,1,0), new = TRUE) # bottom, left, top, and right
par(mfrow=c(1, 1), mar=c(1, 0, 1, 2))
plot(no_prop) ## col = c("#FFFFFF", "#ADB2AC")
plot(land, lwd= 0.5, add = TRUE)

dev.off()


```



Plot of dominant food source:
```{r}

library(scales)
library(rnaturalearth)
library(rnaturalearthdata)

source(here("_workflow/common.R"))
source(here("_workflow/common_spatial.R"))

## save the gall peters projection
gall_peters <- "+proj=cea +lon_0=0 +x_0=0 +y_0=0 +lat_ts=45 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"

## create a water raster
water <- readOGR(dsn = here("_analysis/raw/rgn_all_gcs_med_res.shp"))
water <- water[!water$rgn_nam == "Antarctica",]
proj4string(water) <- CRS("+proj=longlat +datum=WGS84")
water <- spTransform(water, CRS("+proj=cea +lon_0=0 +x_0=0 +y_0=0 +lat_ts=45 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"))
#plot(water)

## create a land raster
land <- ne_countries(scale = "medium", returnclass = "sp") 
land <- land[!land$sov_a3 == "ATA",]
land <- st_as_sf(land)
land <- st_transform(land, crs=gall_peters)
land <- as(land, "Spatial")

land_regions <- raster(file.path(paste(prep, "spatial/gall_peters/food_rgns_gall_peters.tif", sep = "")))
land_regions <- calc(land_regions, function(x) {ifelse(!is.na(x), 1, 0)}) 

n_global_cells <- 14208000
n_land_cells <- cellStats(land_regions, stat = 'sum', na.rm = TRUE)
## 3738004
# n_land_cells/n_global_cells # 0.263, seems right
n_ocean_cells <- n_global_cells-n_land_cells
## 10469996

## plot lower threshold first, then overlay high:

## Land (only plot top 4)
cows_meat_milk_low <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh50_prop_cpi_cows_meat&milk.tif")
# prop of global
prop <- cellStats(cows_meat_milk_low, stat = 'sum')/n_land_cells
prop_global <- cellStats(cows_meat_milk_low, stat = 'sum')/n_global_cells
## 0.1162867 - global prop
## 0.4420009 - land prop

1652201*36
n_land_cells*36
59479236/148940000 # 0.3993503 - land area from google...

crops_low <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh50_prop_cpi_farm_crop.tif")
prop <- cellStats(crops_low, stat = 'sum')/n_land_cells
##   0.2137989 - land prop

shoats_low <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh50_prop_cpi_shoats_meat&milk.tif")
prop <- cellStats(shoats_low, stat = 'sum')/n_land_cells
## 0.1750726 - land prop

chickens_low <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh50_prop_cpi_chickens_eggs&meat.tif")
prop <- cellStats(chickens_low, stat = 'sum')/n_land_cells
##  0.01788709 - land prop

buffaloes_milk_low <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh50_prop_cpi_buffaloes_milk.tif")
prop <- cellStats(buffaloes_milk_low, stat = 'sum')/n_land_cells
## 7.303363e-05 - land prop

pigs_meat_low <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh50_prop_cpi_pigs_meat.tif")
prop <- cellStats(pigs_meat_low, stat = 'sum')/n_land_cells
## 0.02384989 - land prop

fw_low <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh50_prop_cpi_wildcaught_freshwater.tif")
prop <- cellStats(fw_low, stat = 'sum')/n_land_cells
## 0.03035069 - land prop

## Marine (only use top 4 in plot)
dem_fish_low <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh50_prop_cpi_demersal_fisheries.tif")
prop <- cellStats(dem_fish_low, stat = 'sum')/n_ocean_cells
## 0.07416431

fofm_fish_low <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh50_prop_cpi_fofm_fisheries.tif")
prop <- cellStats(fofm_fish_low, stat = 'sum')/n_ocean_cells
## 0.09287406

pell_fish_low <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh50_prop_cpi_large-pelagic_fisheries.tif")
prop <- cellStats(pell_fish_low, stat = 'sum')/n_ocean_cells
## 0.5610258 - ocean prop

pelm_fish_low <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh50_prop_cpi_medium-pelagic_fisheries.tif")
prop <- cellStats(pelm_fish_low, stat = "sum")/n_ocean_cells
## 0.02122713

pels_fish_low <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh50_prop_cpi_small-pelagic_fisheries.tif")
prop <- cellStats(pels_fish_low, stat = "sum")/n_ocean_cells
## 0.001515187

ben_fish_low <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh50_prop_cpi_benthic_fisheries.tif")
prop <- cellStats(ben_fish_low, stat = "sum")/n_ocean_cells
## 0.0008798475

rf_fish_low <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh50_prop_cpi_reef_fisheries.tif")
prop <- cellStats(rf_fish_low, stat = "sum")/n_ocean_cells
## 0.0007292266

mar_low <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh50_prop_cpi_aquaculture_marine.tif")
prop <- cellStats(mar_low, stat = "sum")/n_ocean_cells
## 0.006985963


## high values
cows_meat_milk_high <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh80_prop_cpi_cows_meat&milk.tif")

crops_high <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh80_prop_cpi_farm_crop.tif")

shoats_high <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh80_prop_cpi_shoats_meat&milk.tif")

chickens_high <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh80_prop_cpi_chickens_eggs&meat.tif")

dem_fish_high <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh80_prop_cpi_demersal_fisheries.tif")

fofm_fish_high <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh80_prop_cpi_fofm_fisheries.tif")

pell_fish_high <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh80_prop_cpi_large-pelagic_fisheries.tif")
plot(pell_fish_high)
prop <- cellStats(pell_fish_high, stat = "sum")/n_ocean_cells
##0.4903396

pelm_fish_high <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh80_prop_cpi_medium-pelagic_fisheries.tif")
prop <- cellStats(pelm_fish_high, stat = "sum")/n_ocean_cells
#0.01239638

pels_fish_high <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh80_prop_cpi_small-pelagic_fisheries.tif")
prop <- cellStats(pels_fish_high, stat = "sum")/n_ocean_cells
## 0.0007389688

pels_fish_high <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh80_prop_cpi_small-pelagic_fisheries.tif")
prop <- cellStats(pels_fish_high, stat = "sum")/n_ocean_cells
## 0.0007389688

ben_fish_high <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh80_prop_cpi_benthic_fisheries.tif")
prop <- cellStats(ben_fish_high, stat = "sum")/n_ocean_cells
## 6.59026e-06

rf_fish_high <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh80_prop_cpi_reef_fisheries.tif")
prop <- cellStats(rf_fish_high, stat = "sum")/n_ocean_cells
## 8.242601e-05

mar_high <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/animal_product/prop_cpi_threshold/thresh80_prop_cpi_aquaculture_marine.tif")
prop <- cellStats(mar_high, stat = "sum")/n_ocean_cells
## 0.002353487

## grab a raster that shows where there is any CPI, so that it can be the base layer showing
cpi <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/stressor_summary/equal_area/rescaled/cumulative_stress/all_systems_cumulative_stress.tif")
plot(log(cpi+1))
no_prop <- calc(cpi, fun = function(x){ifelse(x > 0.01, 1, 0)})
plot(no_prop, col = c("#FFFFFF", "#ADB2AC")) ## looks right!

# red, green, orange, blue 
# color_pal <- c('#a33648','#568164', '#d4b057', '#4e6274')
# 
# color_pal_light <- paste0(color_pal, "59")

color_pal <- c("#660C43", "#3CC8C0", "#CC5234", "#EAB33B")
color_pal_light <- paste0(color_pal, "59")

png(here(sprintf("_analysis/figures/paper/output/fig_3_majority_map_a.png", system)), res=500, width=7, height=3, units="in")

par(oma=c(1,1,1,0), new = TRUE) # bottom, left, top, and right
par(mfrow=c(1, 1), mar=c(1, 0, 1, 2))

plot(water, border= "#FFFFFF", col="#FFFFFF", lwd=0.5, main=sprintf("Majority System", system), cex=0.75)
plot(land, border="#BCBEB1", col="#FFFFFF", lwd=0.2, add=TRUE)

#plot(no_prop, col = c("#FFFFFF", "#ADB2AC"), add = TRUE)

plot(cows_meat_milk_low, col=color_pal_light[1], add=TRUE)
plot(cows_meat_milk_high, col=color_pal[1], add=TRUE)

plot(crops_low, col= color_pal_light[2], add=TRUE)
plot(crops_high, col= color_pal[2], add=TRUE)

plot(shoats_low, col=color_pal_light[3], add=TRUE)
plot(shoats_high, col=color_pal[3], add=TRUE)

plot(chickens_low, col=color_pal_light[4], add=TRUE)
plot(chickens_high, col=color_pal[4], add=TRUE)

dev.off()

legend_rasts <- grep("chickens|cows_meat|shoats|crop", dom_food_list_df$raster, value=TRUE)

legend_df <- dom_food_list_df %>%
  filter(raster %in% legend_rasts) %>%
  mutate(food = ifelse(grepl("chickens", .$raster), "chicken meat/eggs & feed", NA),
         food = ifelse(grepl("cows", .$raster), "cow meat & feed", food),
         food = ifelse(grepl("crop", .$raster), "crops, human", food),
         food = ifelse(grepl("shoats", .$raster), "sheep/goats milk/meat & feed", food)) %>%
  mutate(threshold = ifelse(grepl("thresh50", .$raster), ">50%", ">80")) %>%
  cbind(plot_color = c(
    color_pal_light[4], color_pal_light[1], color_pal_light[2],color_pal_light[3],
    color_pal[4], color_pal[1], color_pal[2],color_pal[3])) %>%
  arrange(total_cells) %>% 
  mutate(land_cells = n_land_cells,
         prop = total_cells/land_cells)

library(ggplot2)

mytheme <- theme(axis.line=element_blank(),
                 axis.text.x=element_text(angle=50,hjust=1, size = rel(1.5)),
          axis.text.y=element_blank(),axis.ticks=element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(),legend.position="none",
          panel.background=element_blank(),panel.border=element_blank(),panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),plot.background=element_blank())

p <- ggplot(legend_df, aes(y=total_cells, x= reorder(food, -total_cells), fill=plot_color)) +
  geom_bar(stat="identity", width=1) +
  scale_fill_identity() +
  mytheme 
#  theme_void()
  
ggsave(p, filename = "_analysis/figures/dom_food_legend.png",  bg = "transparent", width = 3, height = 4)


## fisheries

ocean_color_pal <- c("#F86063", "#485178", "#3CC8C0", "#EAB33B")
ocean_color_pal_light <- paste0(ocean_color_pal, "59")

png(here(sprintf("_analysis/figures/paper/output/fig_3_majority_map_a_ocean.png", system)), res=500, width=7, height=3, units="in")

par(oma=c(1,1,1,0), new = TRUE) # bottom, left, top, and right
par(mfrow=c(1, 1), mar=c(1, 0, 1, 2))
plot(water, border= "#F8F9FA", col="#F8F9FA", lwd=0.5, main=sprintf("Majority System Marine", system), cex=0.75)
plot(land, border="#BCBEB1", col="#F8F9FA", lwd=0.2, add=TRUE)

plot(dem_fish_low, col=ocean_color_pal_light[1], add=TRUE)
plot(dem_fish_high, col=ocean_color_pal[1], add=TRUE)

plot(fofm_fish_low, col=ocean_color_pal_light[2], add=TRUE)
plot(fofm_fish_high, col=ocean_color_pal[2], add=TRUE)

plot(pell_fish_low, col=ocean_color_pal_light[3], add=TRUE)
plot(pell_fish_high, col=ocean_color_pal[3], add=TRUE)

plot(pelm_fish_low, col=ocean_color_pal_light[4], add=TRUE)
plot(pelm_fish_high, col=ocean_color_pal[4], add=TRUE)
dev.off()

#cellStats(pell_fish_low, stat = 'sum')/n_ocean_cells

legend_rasts_ocean <- grep("demersal|large-pelagic|medium-pelagic|fofm", dom_food_list_df$raster, value=TRUE)

legend_df_ocean <- dom_food_list_df %>%
  filter(raster %in% legend_rasts_ocean) %>%
  mutate(food = ifelse(grepl("demersal", .$raster), "demersal", NA),
        food = ifelse(grepl("fofm", .$raster), "FOFM", food),
         food = ifelse(grepl("large-pelagic", .$raster), "large pelagic", food),
         food = ifelse(grepl("medium-pelagic", .$raster), "medium pelagic", food)) %>%
  mutate(threshold = ifelse(grepl("thresh50", .$raster), ">50%", ">80%")) %>%
  cbind(plot_color = c(ocean_color_pal_light[1],
                       ocean_color_pal_light[2],
                       ocean_color_pal_light[3],
                       ocean_color_pal_light[4],
                       ocean_color_pal[1],
                       ocean_color_pal[2],
                       ocean_color_pal[3],
                       ocean_color_pal[4])) %>%
  arrange(total_cells)%>% 
  mutate(ocean_cells = n_ocean_cells,
         prop = total_cells/ocean_cells)

p2 <- ggplot(legend_df_ocean, aes(y=total_cells, x= reorder(food, -total_cells), fill=plot_color)) +
  geom_bar(stat="identity", width=1) +
  scale_fill_identity() +
  mytheme 
#  theme_void()
  
ggsave(p2, filename = "_analysis/figures/dom_food_legend_ocean.png",  bg = "transparent", width = 3, height = 4)
```



Plot of dominant stressor
```{r}

land_tif <- "/home/shares/food-systems/Food_footprint/all_food_systems/dataprep/spatial/gall_peters/food_rgns_gall_peters.tif"

stressor_stack <- stack(list.files("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/stressor_summary/equal_area/rescaled/stressors", full=TRUE), land_tif)

stressor_df_int <- as.data.frame(stressor_stack, xy=TRUE) %>% 
  rename(origin = food_rgns_gall_peters) %>% 
  mutate(origin = ifelse(!is.na(origin), "land", "ocean"))

stressor_df_prop<- stressor_df_int %>%
  rowwise() %>%
  mutate(total = sum(c(disturbance, ghg, nutrient, water), na.rm=TRUE))

stressor_df_prop2 <- stressor_df_prop %>%
  rowwise() %>%
  mutate(disturbance_prop = disturbance/total,
         ghg_prop = ghg/total,
         nutrient_prop = nutrient/total,
         water_prop = water/total)

stressor_df_prop3 <- stressor_df_prop2 %>%
  rowwise() %>%
  mutate(dominant_stressor = ifelse(disturbance_prop >= 0.5, 1, NA),
         dominant_stressor = ifelse(ghg_prop >= 0.5, 2, dominant_stressor),
         dominant_stressor = ifelse(nutrient_prop >= 0.5, 3, dominant_stressor),
         dominant_stressor = ifelse(water_prop >= 0.5, 4, dominant_stressor))


# counts <- table(stressor_df_prop3$dominant_stressor)
# counts*36/1000000/510.1
# round((counts*36/510100000)*100,2)

stressor_df_prop4 <- stressor_df_prop3 %>%
  select(x, y, dominant_stressor)

# prop of global
prop <- stressor_df_prop4 %>% 
  as_tibble() %>% 
  mutate(dominant_stressor = ifelse(dominant_stressor == 1, 1, 0)) %>% 
  dplyr::summarise(sum = sum(dominant_stressor, na.rm = TRUE)) %>% 
  mutate(prop = sum/n_global_cells) %>% 
  pull(prop) #0.6202485
  
  # cellStats(cows_meat_low, stat = 'sum')/n_cells

dom_stress <- rasterFromXYZ(stressor_df_prop4)
writeRaster(dom_stress, "/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/dominant_stressor.tif", overwrite = TRUE)

dom_stress <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/figures/dominant_stressor.tif")
# red, green, orange, blue
#color_pal <- c("#aa7828", "#c996a9", "#305E5A", "#97c9ca")
#color_pal <- c('#ac2e48','#31634a', '#d76934', '#052a91')

# color_pal <- c('#9d4158','#5b9d45', '#ce642ac9', '#4254ad58')
# color_pal <- c('#a6611a','#80cdc1', '#dfc27d', '#018571')
# color_pal <- c('#2c7bb6','#abd9e9', '#fdae61', '#d7191c')

#disturbance, ghg, nutrient, water
#color_pal <- c('#d5bd75', '#da6098', '#795b48', '#77c1d7')

#dist, ghg, water, nut 
color_pal <- c("#D5BD75", "#DA6098", "#795B48", "#3E638E")
show_col(color_pal)

## save the map
png(here(sprintf("_analysis/figures/paper/output/fig_3_majority_map_b.png", system)), res=500, width=7, height=3, units="in")

par(oma=c(1,1,1,0), new = TRUE) # bottom, left, top, and right
par(mfrow=c(1, 1), mar=c(1, 0, 1, 2))

plot(water, border= "#F8F9FA", col="#F8F9FA", lwd=0.5, main=sprintf("Majority Stressor", system), cex=0.75)
plot(land, border="#BCBEB1", col="#F8F9FA", lwd=0.2, add=TRUE)
plot(dom_stress, col=c(color_pal[1], color_pal[2], color_pal[3], color_pal[4]), add=TRUE)
#plot(land, lwd=0.2, add=TRUE)
dev.off()

# 1 = disturbance, 2 = ghg, 3 = nutrient, 4 = water

land_counts_df <- stressor_df_prop3 %>% 
  filter(origin == "land") %>% 
  select(dominant_stressor) %>% 
  mutate(stressor = case_when(dominant_stressor == 1 ~ "dist",
                              dominant_stressor == 2 ~ "ghg",
                              dominant_stressor == 3 ~ "nutr",
                              dominant_stressor == 4 ~ "water")) %>% 
  count(stressor) %>% 
  filter(!is.na(stressor)) %>% 
  mutate(plot_color = case_when(stressor == "dist" ~ color_pal[1],
                                stressor == "ghg" ~ color_pal[2],
                                stressor == "nutr" ~ color_pal[3],
                                stressor == "water" ~ color_pal[4]))

land_counts_stats <- land_counts_df %>% 
  mutate(land_cells = n_land_cells,
         prop= n/land_cells)

ocean_counts_df <- stressor_df_prop3 %>% 
  filter(origin == "ocean") %>% 
  select(dominant_stressor) %>% 
  mutate(stressor = case_when(dominant_stressor == 1 ~ "dist",
                              dominant_stressor == 2 ~ "ghg",
                              dominant_stressor == 3 ~ "nutr",
                              dominant_stressor == 4 ~ "water")) %>% 
  count(stressor) %>% 
  filter(!is.na(stressor)) %>% 
  mutate(plot_color = case_when(stressor == "dist" ~ color_pal[1],
                                stressor == "ghg" ~ color_pal[2],
                                stressor == "nutr" ~ color_pal[3],
                                stressor == "water" ~ color_pal[4]))

ocean_counts_stats <- ocean_counts_df %>% 
  mutate(ocean_cells = n_ocean_cells,
         prop= n/ocean_cells)

mytheme <- theme(axis.line=element_blank(),
                 axis.text.x=element_text(angle=50,hjust=1, size = rel(3)),
          axis.text.y=element_blank(),axis.ticks=element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(),legend.position="none",
          panel.background=element_blank(),panel.border=element_blank(),panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),plot.background=element_blank())

land_p <- ggplot(land_counts_df, aes(y=n, x = reorder(stressor, -n), fill=plot_color))+
  geom_bar(stat="identity", width=1) +
  scale_fill_identity() +
  mytheme 
#  theme_void()
  
ggsave(land_p, filename = "_analysis/figures/dom_pressureC_land_legend.png",  bg = "transparent", width = 3, height = 4)

ocean_p <- ggplot(ocean_counts_df, aes(y=n, x= reorder(stressor, -n), fill=plot_color)) +
  geom_bar(stat="identity", width=1) +
  scale_fill_identity() +
  mytheme 
#  theme_void()
  
ggsave(ocean_p, filename = "_analysis/figures/dom_pressureC_ocean_legend.png",  bg = "transparent", width = 3, height = 4)

```