---
title: "Summary stats"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(dplyr)
library(here)

```

## orignal pressures

```{r}
pressures <- read.csv(here("_analysis/checking_data/data/raster_check.csv"))

### disturbance
marine_fish <- grep("marine", pressures$file, value=TRUE)
marine_fish <- grep("disturbance", marine_fish, value=TRUE)
marine_fish <- grep("fisheries", marine_fish, value=TRUE)

marine_fish_disturb <- filter(pressures, file %in% marine_fish)
sum(marine_fish_disturb$sum_cells)
sum(marine_fish_disturb$sum_cells)/17926421
```

## scenario
```{r}
pressures <- read.csv(here("_analysis/scenarios/fisheries_disturbance_raster_check.csv"))

### disturbance
marine_fish <- grep("marine", pressures$file, value=TRUE)
marine_fish <- grep("disturbance", marine_fish, value=TRUE)
marine_fish <- grep("fisheries", marine_fish, value=TRUE)
marine_fish_disturb <- filter(pressures, file %in% marine_fish)
sum(marine_fish_disturb$sum_cells)
sum(marine_fish_disturb$sum_cells)/14638136


```



## original data: all marine pressures
```{r}
pressures <- read.csv(here("_analysis/checking_data/data/raster_check.csv"))

### disturbance
marine_fish <- grep("marine", pressures$file, value=TRUE)
marine_fish <- grep("disturbance", marine_fish, value=TRUE)

marine_fish_disturb <- filter(pressures, file %in% marine_fish) 
sum(marine_fish_disturb$sum_cells)/17926421


## GHG
marine_fish <- grep("marine", pressures$file, value=TRUE)
marine_fish <- grep("ghg", marine_fish, value=TRUE)

marine_fish_disturb <- filter(pressures, file %in% marine_fish)
sum(marine_fish_disturb$sum_cells)/6480794762

## nutrient
marine_fish <- grep("marine", pressures$file, value=TRUE)
marine_fish <- grep("nutrient", marine_fish, value=TRUE)

marine_fish_disturb <- filter(pressures, file %in% marine_fish)
sum(marine_fish_disturb$sum_cells)/143686157


mean(c(31.4, 6.57, 1, 0))

```

## scenario data
```{r}
pressures <- read.csv(here("_analysis/scenarios/fisheries_disturbance_raster_check.csv"))

### disturbance
marine_fish <- grep("marine", pressures$file, value=TRUE)
marine_fish <- grep("disturbance", marine_fish, value=TRUE)

marine_fish_disturb <- filter(pressures, file %in% marine_fish)
sum(marine_fish_disturb$sum_cells)/14638136


## GHG
marine_fish <- grep("marine", pressures$file, value=TRUE)
marine_fish <- grep("ghg", marine_fish, value=TRUE)

marine_fish_disturb <- filter(pressures, file %in% marine_fish)
sum(marine_fish_disturb$sum_cells)/6480794762

## nutrient
marine_fish <- grep("marine", pressures$file, value=TRUE)
marine_fish <- grep("nutrient", marine_fish, value=TRUE)

marine_fish_disturb <- filter(pressures, file %in% marine_fish)
sum(marine_fish_disturb$sum_cells)/143686157


mean(c(16, 6.57, 1, 0))

```


demersal fishing cumulative pressures
```{r}

pressures <- read.csv(here("_analysis/scenarios/fisheries_disturbance_raster_check.csv"))

### disturbance
marine_fish <- grep("marine_demersal_fisheries_meat", pressures$file, value=TRUE)

marine_fish_disturb <- filter(pressures, file %in% marine_fish)

831640.8/14638136
187363384.7/6480794761
mean(c(0, 0, 0.0568133, 0.02891056))

## 0.021
```

```{r}

pressures <- read.csv(here("_analysis/checking_data/data/raster_check.csv"))

### disturbance
marine_fish <- grep("marine_demersal_fisheries_meat", pressures$file, value=TRUE)

marine_fish_disturb <- filter(pressures, file %in% marine_fish)

2433457/17926420
187363384.7/6480794761
mean(c(0, 0, 0.135747, 0.02891056))

```


sheep cumulative pressures
```{r}

pressures <- read.csv(here("_analysis/scenarios/fisheries_disturbance_raster_check.csv"))

### disturbance
marine_fish <- grep("sheep", pressures$file, value=TRUE)
marine_fish <- grep("_x_", marine_fish, value=TRUE, invert=TRUE)
marine_fish <- grep("meat", marine_fish, value=TRUE)

marine_fish_disturb <- filter(pressures, file %in% marine_fish)
  

(4.970692e+04 + 2.291838e+03)/14638136
(6.488098e+07 + 1.015290e+08)/6480794761
(2.479593e+06 + 3.685651e+06)/143686157
(9.513381e+08 + 1.527360e+09)/10048617266436.633
mean(c( 0.00355228, 0.0256774, 0.04290771, 0.0002466706))

read_csv("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/raw_df_summary/rgn_raw_summary.csv") %>%
  filter(organism=="sheep" & product == "meat") %>%
  group_by(pressure) %>%
  summarize(total=sum(sum))
           
  mean(c( 61650/17926420,
   170204542/6480794761,
   6188684/143686156,
   27337630682/10048617266436))
 mean(c(0.002900691, 0.0256774, 0.04290771, 0.0002466706) ) 
           c("feedcrop", "feedfodd"))

## 0.019
```

```{r}

pressures <- read.csv(here("_analysis/checking_data/data/raster_check.csv"))

### disturbance
marine_fish <- grep("marine_demersal_fisheries_meat", pressures$file, value=TRUE)

marine_fish_disturb <- filter(pressures, file %in% marine_fish)

2433457/17926420
187363384.7/6480794761
mean(c(0, 0, 0.135747, 0.02891056))

```